### ISSUE TITLE
Glixxzy stealing your code again

### ISSUE THREAD

**Issue by FireyKitKat** [rxzyx/Blooket-Hacks#11]
Glixxzy stole your crypto hacks now
there are no difference between the hacks
![Screenshot 2022-06-16 11 13 23 PM](https://user-images.githubusercontent.com/106935277/174217763-63019982-b503-483f-a093-ef7b23c919ad.png)
![Screenshot 2022-06-16 11 13 21 PM](https://user-images.githubusercontent.com/106935277/174217773-783307a2-46ad-44d2-9bb8-c2dc3a62f415.png)

![Screenshot 2022-06-16 11 13 35 PM](https://user-images.githubusercontent.com/106935277/174217733-935f5b87-ed85-416a-9cfb-7f890bd4d5d6.png)
![Screenshot 2022-06-16 11 13 33 PM](https://user-images.githubusercontent.com/106935277/174217749-58d42de2-44f7-4db5-8638-a2c8200e6d60.png)

**Comment by rxzyx** [comment]
Yes I know.

**Comment by rxzyx** [comment]
He blocked me from putting comments. And banned me on Discord.

**Comment by FireyKitKat** [comment]
Same, I put a issue telling him to stop stealing code from you but he just deleted the issue.

**Comment by yedonbro** [comment]
Hey... I went on his discord and posted a link to this issue

**Comment by rxzyx** [comment]
Thank you! But he'll just ban you, happened to me.

**Comment by rxzyx** [comment]
Also he stole my flood bots hack and re-obfuscated it to make it look like it was his.

**Comment by VillainsRule4000** [comment]
@rxzyx He unbanned me from commenting on his Github repo.

ACTUALLY GLIXXZZY QUOTES:
```
I'm the real one.
I wanted to clear some things up about Lol-Jude
So, here's the story: I got a c&d from Ben the CEO of Blooket NOT because of my hacks, whole different story so I got banned from GitHub etc. I had someone take over until it was safe to come back which was Lol, I provided my hacks to him directly and etc, when he got into the "stealing from school cheats stuff" I swooped in and took back over.
After this rzy or whoever made photoshopped screenshots of me "taking his hacks" and etc
now i'm here trying to clear this up to you
```

**Comment by rxzyx** [comment]
“PHOTOSHOPPED”??? IT’S ON HIS GITHUB

**Comment by VillainsRule4000** [comment]
IKRRRRRRRR!

**Comment by VillainsRule4000** [comment]
me back:
```
What about how you Crypto Hack ones are the EXACT SAME as rxzyx's?
https://github.com/rxzyx/Blooket-Hacks/issues/11
Like
That's not actually photoshopped
Are you LYING to me, like I was told by all of the other people?
```

**Comment by VillainsRule4000** [comment]
OOOOOOH

**Comment by rxzyx** [comment]
He also took my deceptive dinos hack and my flood bots hack

**Comment by yedonbro** [comment]
its gone LOL

**Comment by yedonbro** [comment]
BTW glizzy's github wayback machine page is a thing
