### ISSUE TITLE
Candy Rush/Gold Rush Bug

### ISSUE THREAD

**Issue by paperclipity** [rxzyx/Blooket-Hacks#110]
*I only tested Candy Rush*

> Bug

When you use the [ChestESP](https://github.com/rxzyx/Blooket-Hacks/blob/main/Candy%20Quest/Chest%20ESP.js), it works, but the Money Display glitches. It will never change. I don't know if it was just me.

**Comment by VitalTencelll** [comment]
> _I only tested Candy Rush_
> 
> > Bug
> 
> When you use the [ChestESP](https://github.com/rxzyx/Blooket-Hacks/blob/main/Candy%20Quest/Chest%20ESP.js), it works, but the Money Display glitches. It will never change. I don't know if it was just me.

No, it's not just you. I've been using this and the candy display stays to 0. I'm pretty sure rxzyx would fix it by now or next week. All we have to do now is be patient and wait.

**Comment by rxzyx** [comment]
Really? Didn’t happen with me. I’ll look into it.

**Comment by VitalTencelll** [comment]
> Really? Didn’t happen with me. I’ll look into it.

Alright, thanks.
