### ISSUE TITLE
Make spam open boxes hack please

### ISSUE THREAD

**Issue by 4200hahafunnyxd** [rxzyx/Blooket-Hacks#111]
**Describe the bug**

**To Reproduce**
Run the code, if there is an error, provide a screenshot or copy the error. However, if there is no error but it doesn't work then show the url on where it was made and how you ran the code.

**Comment by Wilke000** [comment]
Not an error pls close

**Comment by TheBobCreator** [comment]
stop, this is NOT AN ISSUE!!!!!!!!!

**Comment by TheBobCreator** [comment]
Note for everyone: don't submit issues that are actually REQUESTS.

**Comment by tatertot0911** [comment]
IT'S IMPOSSIBLE TO DO SPAM OPEN BOXES

**Comment by Wilke000** [comment]
thats not true

**Comment by ZackiBoiz** [comment]
False issue. Not a bug.

**Comment by BlooketHeck** [comment]
not a bug

**Comment by VillainsRule4000** [comment]
@rxzyx close.

**Comment by rxzyx** [comment]
False issue.
