### ISSUE TITLE
Flappy Bird Not Working

### ISSUE THREAD

**Issue by BlooketHeck** [rxzyx/Blooket-Hacks#113]
Whenever I try using the [Flappy Bird](https://github.com/rxzyx/Blooket-Hacks/tree/main/Flappy%20Bird) hacks it never works, idk if I'm using it wrong.

**Comment by VillainsRule4000** [comment]
Could you screen record you using it and failing?
Mac: https://support.apple.com/en-us/HT208721
Chrome: https://support.google.com/chromebook/answer/10474268?hl=en
Windows: https://www.tomshardware.com/how-to/screen-record-in-windows#:~:text=Hit%20the%20Windows%20Key%20%2B%20Alt,most%20likely%20in%20a%20corner.

**Comment by BlooketHeck** [comment]
> Could you screen record you using it and failing? Mac: https://support.apple.com/en-us/HT208721 Chrome: https://support.google.com/chromebook/answer/10474268?hl=en Windows: https://www.tomshardware.com/how-to/screen-record-in-windows#:~:text=Hit%20the%20Windows%20Key%20%2B%20Alt,most%20likely%20in%20a%20corner.

[Screen recording 2022-10-26 8.41.33 PM.webm](https://user-images.githubusercontent.com/94115787/198164755-765d37ee-d487-494f-a57c-14401466bc01.webm) It may look like I didn't put in the code but  I did

**Comment by VillainsRule4000** [comment]
Fixed in #116.
