### ISSUE TITLE
Chest ESP.js

### ISSUE THREAD

**Issue by NathanBollard** [rxzyx/Blooket-Hacks#115]
Rename [_"Candy Quest/**Chest ESP.js**"_](https://github.com/rxzyx/Blooket-Hacks/blob/main/Candy%20Quest/Chest%20ESP.js) to _'Candy Quest/**Pumpkin ESP.js**'_.

**Comment by VillainsRule4000** [comment]
done in a PR

**Comment by VillainsRule4000** [comment]
Fixed in #116.

**Comment by NathanBollard** [comment]
Thanks!

**Comment by NathanBollard** [comment]
a

**Comment by Wilke000** [comment]
No don’t because they are the same thing and will be switched back soon

**Comment by rxzyx** [comment]
False issue.
