### ISSUE TITLE
Remove Pipes.js

### ISSUE THREAD

**Issue by NathanBollard** [rxzyx/Blooket-Hacks#117]
[Remove Pipes.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Flappy%20Bird/Remove%20Pipes.js) does not work.

#113 #88 #32

**Comment by rxzyx** [comment]
Ask @notzastix. And also pretty sure this is a false issue.

**Comment by notzastix** [comment]
It works perfectly fine.
