### ISSUE TITLE
Get all questions correct doesn't work in battle royale

### ISSUE THREAD

**Issue by LordofPengiun** [rxzyx/Blooket-Hacks#120]
**Describe the bug**

**To Reproduce**
Run the code, if there is an error, provide a screenshot or copy the error. However, if there is no error but it doesn't work then show the url on where it was made and how you ran the code.

**Comment by rxzyx** [comment]
False issue. Will test later again.

**Comment by Wilke000** [comment]
Yea battle Royale for some reason can’t be hacked I think

**Comment by rxzyx** [comment]
Ok.
