### ISSUE TITLE
Custom Blooks.js does not work

### ISSUE THREAD

**Issue by BlooketHeck** [rxzyx/Blooket-Hacks#124]
[Custom Blooks.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Custom%20Blooks.js) Does not work 
[Uploading Screen recording 2022-10-27 3.48.09 PM.webm…]()

**Comment by ZackiBoiz** [comment]
@BlooketHeck That video didn't link up...

(Custom Blooks.js)[https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Custom%20Blooks.js] does work. There isn't a proper way to get IDs however. I will be making a way to get IDs.

If this didn't help, please restate the problem.

**Comment by BlooketHeck** [comment]
[Screen recording 2022-10-27 3.48.09 PM.webm](https://user-images.githubusercontent.com/94115787/198385925-d1966843-4cde-4d62-a368-14547c51879a.webm) Try this one

**Comment by VitalTencelll** [comment]
You have to host and play then do it for it to work

**Comment by ZackiBoiz** [comment]
@VitalTencelll No, this is not "Get Any Blook"

**Comment by ZackiBoiz** [comment]
@BlooketHeck That is my fault, as I put a comment block in the script. I'll update that. Try running it without the comments.

**Comment by BlooketHeck** [comment]
@ZackiBoiz Could you tell me what line to avoid?

**Comment by BlooketHeck** [comment]
Sorry, complete noob question, but what is a comment block?

**Comment by ZackiBoiz** [comment]
Delete the lines with "//" at the beginning.

**Comment by BlooketHeck** [comment]
Ok

**Comment by ZackiBoiz** [comment]
I made a merge request to update it.

**Comment by BlooketHeck** [comment]
It still doesn't work

**Comment by ZackiBoiz** [comment]
@BlooketHeck Send a video.

**Comment by ZackiBoiz** [comment]
nevermind, I see the issue

**Comment by BlooketHeck** [comment]
[Screen recording 2022-10-27 4.10.21 PM.webm](https://user-images.githubusercontent.com/94115787/198388586-cf75f0ac-fe67-4eed-9664-b81177c9679b.webm)

**Comment by BlooketHeck** [comment]
@ZackiBoiz What is the issue?

**Comment by ZackiBoiz** [comment]
@BlooketHeck Yes, I see. I just changed the pull req. And, also, if you want to copy that code, see it [here](https://github.com/rxzyx/Blooket-Hacks/blob/c55164f1f8c3af5132619c2d00266653018294d9/Default%20Scripts/Custom%20Blooks.js)

**Comment by ZackiBoiz** [comment]
@BlooketHeck The issue was the prompts.

**Comment by BlooketHeck** [comment]
It works but its only a sploof

**Comment by ZackiBoiz** [comment]
It is perm.

**Comment by ZackiBoiz** [comment]
Forever

**Comment by ZackiBoiz** [comment]
oh wait. its not...

**Comment by ZackiBoiz** [comment]
> It works but its only a sploof

Yeah

**Comment by ZackiBoiz** [comment]
If you have an account that has all of the items unlocked, it will be permanent.

**Comment by ZackiBoiz** [comment]
It only is permanent if you have all of those items, and if you press "edit" and then "save"

**Comment by VitalTencelll** [comment]
> @VitalTencelll No, this is not "Get Any Blook"

Oh

**Comment by NathanBollard** [comment]
> It only is permanent if you have all of those items, and if you press "edit" and then "save"

Permanent? Like you can't change it manually after inputting the custom Blooks?

**Comment by ZackiBoiz** [comment]
@NathanBollard No, you can change it. It "doesn't delete" is what I meant.

**Comment by NathanBollard** [comment]
> @NathanBollard No, you can change it. It "doesn't delete" is what I meant.

Whew.
