### ISSUE TITLE
Add Rewards doesn't work

### ISSUE THREAD

**Issue by E10DezNuts** [rxzyx/Blooket-Hacks#125]
Add rewards doesn't work,. Is it just me?

**Comment by ZackiBoiz** [comment]
@E10DezNuts Send a video of you using it so I can replicate the bug

**Comment by VitalTencelll** [comment]
Yes, you have to go to blooket.com/play maybe

**Comment by ZackiBoiz** [comment]
@VitalTencelll correct.

**Comment by VitalTencelll** [comment]
I'm always correct hehehe

**Comment by VillainsRule4000** [comment]
Try @GooseterV's script

**Comment by rxzyx** [comment]
False issue.
