### ISSUE TITLE
Custom Blook

### ISSUE THREAD

**Issue by probablyaarxn** [rxzyx/Blooket-Hacks#128]
Hey, could you explain to me the process of this. I've read the whole issue previous to mine, but I dont understand how it was resolved. How do I get the blook code, what do I use to make the blook, and what are the conditions of where it will last and how I will be able to use it.

**Comment by NathanBollard** [comment]
Unrelated, but how did you label that? I don't know how.

**Comment by BlooketHeck** [comment]
#124 @ZackiBoiz is working on a tutorial on how to get the ID

**Comment by BlooketHeck** [comment]
@rxzyx close

**Comment by NathanBollard** [comment]
> Unrelated, but how did you label that? I don't know how.

How do you actually label issues tho

**Comment by probablyaarxn** [comment]
thanks man

**Comment by probablyaarxn** [comment]
also while we're here, what is Manipulate Plus?

**Comment by NathanBollard** [comment]
> also while we're here, what is Manipulate Plus?

Look in README.md.

**Comment by NathanBollard** [comment]
> > also while we're here, what is Manipulate Plus?
> 
> Look in README.md.

Basically what it says is that you can access modes that only Plus or Plus Flex members can. Manipulate Plus.js was created because of the first week Monster Brawl was out.

**Comment by rxzyx** [comment]
Being developed by @ZackiBoiz. Hack will be improved.

**Comment by ZackiBoiz** [comment]
> Being developed by @ZackiBoiz. Hack will be improved.

@probablyaarxn Just as @rxzyx said, yes, I will improve this.
