### ISSUE TITLE
Anti-Ban & Tampermonkey

### ISSUE THREAD

**Issue by VillainsRule4000** [rxzyx/Blooket-Hacks#13]
Tampermonkey does not allow obfuscated scripts. You may have to unobfuscate the parts that show the name, author, etc.

**Comment by rxzyx** [comment]
Alright.

**Comment by rxzyx** [comment]
https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Tamper%20Monkey/Anti-Ban.js
