### ISSUE TITLE
Flood Game.js

### ISSUE THREAD

**Issue by NathanBollard** [rxzyx/Blooket-Hacks#132]
[Flood Game.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Flood%20Game.js) does not work.

[Screen recording 2022-10-27 4.56.23 PM.webm](https://user-images.githubusercontent.com/116772462/198418912-daefb7f8-d5b5-4f05-9252-f6b363656a4a.webm)

## References
#119 #61 #56 #6

**Comment by rxzyx** [comment]
Can’t view the video. I’ll check later.

**Comment by rxzyx** [comment]
I made it slower because before it wasn’t working, so looks like it has to be even slower.
