### ISSUE TITLE
Custom Blooks

### ISSUE THREAD

**Issue by Wilke000** [rxzyx/Blooket-Hacks#134]
In the readme, the custom blooks link leads to this:
<img width="1436" alt="Screenshot 2022-10-28 at 1 34 39 PM" src="https://user-images.githubusercontent.com/85253703/198698060-fcd0f3d3-a75e-47a8-90dd-129736d43da9.png">

(the top one)
<img width="792" alt="Screenshot 2022-10-28 at 1 34 19 PM" src="https://user-images.githubusercontent.com/85253703/198698013-be919879-8846-42f1-bd61-7ea5fe8b071c.png">

**Comment by rxzyx** [comment]
Thanks. Error from @ZackiBoiz.

**Comment by rxzyx** [comment]
Looks like a false issue. Please refresh the README.MD.

**Comment by Wilke000** [comment]
no look
    - <a href="https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Host/Custom%20BlookS.js">Custom BlookS</a> - Sets your custom Blooks using IDs.

**Comment by rxzyx** [comment]
^ I know. I deleted my message.

**Comment by rxzyx** [comment]
Also @NathanBollard made the issue.

**Comment by ZackiBoiz** [comment]
Yeah, sorry about that.

**Comment by NathanBollard** [comment]
Sorry, that was an accident. :(
