### ISSUE TITLE
This is not an issue, more of a request

### ISSUE THREAD

**Issue by AdrienHacker** [rxzyx/Blooket-Hacks#137]
Is there a way to reset the daily limit, so I could use Get Tokens twice or more a day.

**Comment by rxzyx** [comment]
Not an issue. And no.

**Comment by AdrienHacker** [comment]
why

**Comment by AdrienHacker** [comment]
is it possible

**Comment by rxzyx** [comment]
Sever sided.

**Comment by AdrienHacker** [comment]
Oh, okay thanks 
I like it how you reply to issues instantly

**Comment by AdrienHacker** [comment]
By
