### ISSUE TITLE
[Suggestion] Select Any Blook Icon.js 

### ISSUE THREAD

**Issue by NathanBollard** [rxzyx/Blooket-Hacks#140]
I have a suggestion. Right now, Select Any Blook.js let's you, select any Blook, in the game lobby. What if there was a way to select any Blook in the Blook icon in Stats? And, for an addition, allow to choose current custom Blooks too!

**Comment by rxzyx** [comment]
False issue.

**Comment by NathanBollard** [comment]
Because it's a suggestion!

**Comment by NathanBollard** [comment]
Do you know what a suggestion is?

**Comment by VillainsRule4000** [comment]
Join the discord.

**Comment by NathanBollard** [comment]
Oh.
