### ISSUE TITLE
Set Score.js

### ISSUE THREAD

**Issue by NathanBollard** [rxzyx/Blooket-Hacks#141]
[Set Score.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Flappy%20Bird/Set%20Score.js) does not work.

## References
#118 #113 #88 #32

**Comment by NathanBollard** [comment]
Proof:
[Screen recording 2022-10-30 4.01.30 PM.webm](https://user-images.githubusercontent.com/116772462/198906043-d73ae226-97a2-407c-8522-3274484873e6.webm)

**Comment by NathanBollard** [comment]
Proof:
[Video](https://user-images.githubusercontent.com/116772462/198906139-e6643a3d-af70-413a-909e-ffdf121e5e28.webm)

**Comment by rxzyx** [comment]
“Closed this as completed”.

**Comment by notzastix** [comment]
can you show a picture of the console if possible?
seems to work fine for me

**Comment by NathanBollard** [comment]
?
