### ISSUE TITLE
Please add this

### ISSUE THREAD

**Issue by Dentamon** [rxzyx/Blooket-Hacks#155]
Can you add spam boxes?

**Comment by rxzyx** [comment]
Not an issue. Blocked.

**Comment by rxzyx** [comment]
Next false issue is a block.

**Comment by VillainsRule4000** [comment]
You should add Spam Boxes though

**Comment by VillainsRule4000** [comment]
It's a good hack

**Comment by VillainsRule4000** [comment]
@Dentamon https://github.com/Minesraft2/Blooket-Cheats for a spam boxes :)

**Comment by rxzyx** [comment]
Deleted for advertisement.

**Comment by rxzyx** [comment]
Ok, but this is not how to get your message across.

**Comment by VillainsRule4000** [comment]
Some people don't have Discord.

**Comment by Dentamon** [comment]
ye do you have guilded
