### ISSUE TITLE
⚠️ READ BEFORE ISSUE ⚠️

### ISSUE THREAD

**Issue by VillainsRule4000** [rxzyx/Blooket-Hacks#156]
## Hack(s) Not Working
First...
1. Check the Pull Requests to make sure none are open that modify the hack.
2. Make sure you are using the latest version

**If these have been done, open a issue and...**
1. Add a link to the hack.
2. Screenshot console errors (if possible)

**Comment by rxzyx** [comment]
Ok. I will add this later.

**Comment by rxzyx** [comment]
Thanks.

**Comment by ZackiBoiz** [comment]
Pin this

**Comment by rxzyx** [comment]
Oh alr. Thought you meant template.

**Comment by NathanBollard** [comment]
Thank you!

**Comment by NathanBollard** [comment]
> ## Hack(s) Not Working
> First...
> 
> 1. Check the Pull Requests to make sure none are open that modify the hack.
> 2. Make sure you are using the latest version
> 
> **If these have been done, open a issue and...**
> 
> 1. Add a link to the hack.
> 2. Screenshot console errors (if possible)
> 
> ## Making a Screen Recording
> This depends on your device.
> 
> * Mac (best device) > https://support.apple.com/en-us/HT208721
> * Windows > https://www.tomshardware.com/how-to/screen-record-in-windows#:~:text=Hit%20the%20Windows%20Key%20%2B%20Alt,most%20likely%20in%20a%20corner.
> * Chromebook > https://support.google.com/chromebook/answer/10474268

@VillainsRule4000, can you edit this to remove " (best device)"? It might be your opinion, but it's not the right place.

**Comment by VillainsRule4000** [comment]
> @VillainsRule4000, can you edit this to remove " (best device)"? It might be your opinion, but it's not the right place.

it's true, macs have better security, faster performance, and are overall the best devices.
you know because they cost the most.

**Comment by VillainsRule4000** [comment]
> > > @VillainsRule4000, can you edit this to remove " (best device)"? It might be your opinion, but it's not the right place.
> > 
> > 
> > it's true, macs have better security, faster performance, and are overall the best devices. you know because they cost the most.
> 
> It doesn't matter. Just remove it please

windows user, how cringe

**Comment by unknown578** [comment]
um how do i give myself a blook? idk how to

**Comment by NathanBollard** [comment]
> um how do i give myself a blook? idk how to

Wrong issue.

**Comment by NathanBollard** [comment]
> ## Hack(s) Not Working
> First...
> 
> 1. Check the Pull Requests to make sure none are open that modify the hack.
> 2. Make sure you are using the latest version
> 
> **If these have been done, open a issue and...**
> 
> 1. Add a link to the hack.
> 2. Screenshot console errors (if possible)
> 
> ## Making a Screen Recording
> This depends on your device.
> 
> * Mac (best device) > https://support.apple.com/en-us/HT208721
> * Windows > https://www.tomshardware.com/how-to/screen-record-in-windows#:~:text=Hit%20the%20Windows%20Key%20%2B%20Alt,most%20likely%20in%20a%20corner.
> * Chromebook > https://support.google.com/chromebook/answer/10474268

Grammar issue. I suggest changing "If these have been done, open a issue and..." to "If these have been done, open an issue and...". Summary: "a issue" --> "an issue". *(Might as well just do it before anyone else notices this grammatical issue.)*

**Comment by VillainsRule4000** [comment]
idc 🤣 all you care about is how it looks
you can read it if you can read

**Comment by NathanBollard** [comment]
> idc 🤣 all you care about is how it looks you can read it if you can read

Congrats, now you can say you've authorized a pinned haphazard. Just change it plz

**Comment by NathanBollard** [comment]
I made a Pull Request similar to this issue's point. It's #207.

**Comment by VillainsRule4000** [comment]
updated the issue

**Comment by NathanBollard** [comment]
> updated the issue

The Screen Recording area seems a little complicated. You can use this instead:

* Mac > Shift + Cmd ⌘ + 5
* Windows > ⊞ Win + Alt + R
* Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)

**Comment by VillainsRule4000** [comment]
> > updated the issue
> 
> The Screen Recording area seems a little complicated. You can use this instead:
> 
> * Mac > Shift + Cmd ⌘ + 5
> * Windows > ⊞ Win + Alt + R
> * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)

It's fine. You care too much about how stuff looks.
~~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~~

**Comment by NathanBollard** [comment]
> > > updated the issue
> > 
> > 
> > The Screen Recording area seems a little complicated. You can use this instead:
> > 
> > * Mac > Shift + Cmd ⌘ + 5
> > * Windows > ⊞ Win + Alt + R
> > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> 
> It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~

Why do you need to have a full 920x160 image to show Shift + Cmd ⌘ + 5?

**Comment by VillainsRule4000** [comment]
> > > > updated the issue
> > > 
> > > 
> > > The Screen Recording area seems a little complicated. You can use this instead:
> > > 
> > > * Mac > Shift + Cmd ⌘ + 5
> > > * Windows > ⊞ Win + Alt + R
> > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > 
> > 
> > It's fine. You care too much about how stuff looks.
> 
> Why do you need to have a full 920x160 image to show Shift + Cmd ⌘ + 5? Plus, the one who's saying that is the author of #208.

1. it's copied and pasted from apple's support center
2. #208 is for the use of coding platforms that don't recognize them. https://www.google.com/search?q=should+I+put+spaces+in+file+names

**Comment by NathanBollard** [comment]
> > > > > updated the issue
> > > > 
> > > > 
> > > > The Screen Recording area seems a little complicated. You can use this instead:
> > > > 
> > > > * Mac > Shift + Cmd ⌘ + 5
> > > > * Windows > ⊞ Win + Alt + R
> > > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > > 
> > > 
> > > It's fine. You care too much about how stuff looks.
> > 
> > 
> > Why do you need to have a full 920x160 image to show Shift + Cmd ⌘ + 5? Plus, the one who's saying that is the author of #208.
> 
> 1. it's copied and pasted from apple's support center
> 2. [Improper Filenames #208](https://github.com/rxzyx/Blooket-Hacks/issues/208) is for the use of coding platforms that don't recognize them. https://www.google.com/search?q=should+I+put+spaces+in+file+names

1. It doesn't matter (at all) if it's from Apple's support center. When I was making #207, I used it, then later removed it since it was too big. I tried minimizing the height of the image to 24px, (with lock ratio, of course), and the image's buttons' text were unreadable. That led me to using characters to show it, (discluding the Show Windows button.)
2. THAT'S NOT EVEN RELATED!

**Comment by NathanBollard** [comment]
> > > updated the issue
> > 
> > 
> > The Screen Recording area seems a little complicated. You can use this instead:
> > 
> > * Mac > Shift + Cmd ⌘ + 5
> > * Windows > ⊞ Win + Alt + R
> > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> 
> It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~

Please don't reply with swears to me.

**Comment by VillainsRule4000** [comment]
> > > > updated the issue
> > > 
> > > 
> > > The Screen Recording area seems a little complicated. You can use this instead:
> > > 
> > > * Mac > Shift + Cmd ⌘ + 5
> > > * Windows > ⊞ Win + Alt + R
> > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > 
> > 
> > It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~
> 
> Please don't reply with swears to me.

pls don't annoy me

**Comment by NathanBollard** [comment]
> > > > > updated the issue
> > > > 
> > > > 
> > > > The Screen Recording area seems a little complicated. You can use this instead:
> > > > 
> > > > * Mac > Shift + Cmd ⌘ + 5
> > > > * Windows > ⊞ Win + Alt + R
> > > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > > 
> > > 
> > > It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~
> > 
> > 
> > Please don't reply with swears to me.
> 
> pls don't annoy me

If I annoy you, that comes from your opinion.

**Comment by VillainsRule4000** [comment]
> > > > > > updated the issue
> > > > > 
> > > > > 
> > > > > The Screen Recording area seems a little complicated. You can use this instead:
> > > > > 
> > > > > * Mac > Shift + Cmd ⌘ + 5
> > > > > * Windows > ⊞ Win + Alt + R
> > > > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > > > 
> > > > 
> > > > It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~
> > > 
> > > 
> > > Please don't reply with swears to me.
> > 
> > 
> > pls don't annoy me
> 
> If I annoy you, that comes from your opinion.

if my words are swears, that comes from your opinion

**Comment by NathanBollard** [comment]
> > > > > > > updated the issue
> > > > > > 
> > > > > > 
> > > > > > The Screen Recording area seems a little complicated. You can use this instead:
> > > > > > 
> > > > > > * Mac > Shift + Cmd ⌘ + 5
> > > > > > * Windows > ⊞ Win + Alt + R
> > > > > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > > > > 
> > > > > 
> > > > > It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~
> > > > 
> > > > 
> > > > Please don't reply with swears to me.
> > > 
> > > 
> > > pls don't annoy me
> > 
> > 
> > If I annoy you, that comes from your opinion.
> 
> if my words are swears, that comes from your opinion

No, it doesn't. Swearing is when you say a word that is defined as swearing.

**Comment by VillainsRule4000** [comment]
> > > > > > > > updated the issue
> > > > > > > 
> > > > > > > 
> > > > > > > The Screen Recording area seems a little complicated. You can use this instead:
> > > > > > > 
> > > > > > > * Mac > Shift + Cmd ⌘ + 5
> > > > > > > * Windows > ⊞ Win + Alt + R
> > > > > > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > > > > > 
> > > > > > 
> > > > > > It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~
> > > > > 
> > > > > 
> > > > > Please don't reply with swears to me.
> > > > 
> > > > 
> > > > pls don't annoy me
> > > 
> > > 
> > > If I annoy you, that comes from your opinion.
> > 
> > 
> > if my words are swears, that comes from your opinion
> 
> No, it doesn't. Swearing is when you say a word that is defined as swearing.

defined as swearing by who?

**Comment by NathanBollard** [comment]
> > > > > > > > > updated the issue
> > > > > > > > 
> > > > > > > > 
> > > > > > > > The Screen Recording area seems a little complicated. You can use this instead:
> > > > > > > > 
> > > > > > > > * Mac > Shift + Cmd ⌘ + 5
> > > > > > > > * Windows > ⊞ Win + Alt + R
> > > > > > > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > > > > > > 
> > > > > > > 
> > > > > > > It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~
> > > > > > 
> > > > > > 
> > > > > > Please don't reply with swears to me.
> > > > > 
> > > > > 
> > > > > pls don't annoy me
> > > > 
> > > > 
> > > > If I annoy you, that comes from your opinion.
> > > 
> > > 
> > > if my words are swears, that comes from your opinion
> > 
> > 
> > No, it doesn't. Swearing is when you say a word that is defined as swearing.
> 
> defined as swearing by who?

America.

**Comment by VillainsRule4000** [comment]
> > > > > > > > > > updated the issue
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > The Screen Recording area seems a little complicated. You can use this instead:
> > > > > > > > > 
> > > > > > > > > * Mac > Shift + Cmd ⌘ + 5
> > > > > > > > > * Windows > ⊞ Win + Alt + R
> > > > > > > > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~
> > > > > > > 
> > > > > > > 
> > > > > > > Please don't reply with swears to me.
> > > > > > 
> > > > > > 
> > > > > > pls don't annoy me
> > > > > 
> > > > > 
> > > > > If I annoy you, that comes from your opinion.
> > > > 
> > > > 
> > > > if my words are swears, that comes from your opinion
> > > 
> > > 
> > > No, it doesn't. Swearing is when you say a word that is defined as swearing.
> > 
> > 
> > defined as swearing by who?
> 
> Officialments.

that's not a word

**Comment by NathanBollard** [comment]
> > > > > > > > > > > updated the issue
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > The Screen Recording area seems a little complicated. You can use this instead:
> > > > > > > > > > 
> > > > > > > > > > * Mac > Shift + Cmd ⌘ + 5
> > > > > > > > > > * Windows > ⊞ Win + Alt + R
> > > > > > > > > > * Chromebook > Shift + Ctrl + ![](https://user-images.githubusercontent.com/116772462/201830254-e3b8df4c-fbc5-4b5d-911a-cbf769a56669.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It's fine. You care too much about how stuff looks. ~btw who has the rock as a pfp in 2022 you're stuck in 2020 like tf?~
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Please don't reply with swears to me.
> > > > > > > 
> > > > > > > 
> > > > > > > pls don't annoy me
> > > > > > 
> > > > > > 
> > > > > > If I annoy you, that comes from your opinion.
> > > > > 
> > > > > 
> > > > > if my words are swears, that comes from your opinion
> > > > 
> > > > 
> > > > No, it doesn't. Swearing is when you say a word that is defined as swearing.
> > > 
> > > 
> > > defined as swearing by who?
> > 
> > 
> > Officialments.
> 
> that's not a word

I'm going to stop chaining now. (See the edit.)

**Comment by rxzyx** [comment]
Disclaimer: Because the discord server is no longer available, you can now make an 'issue' in the form of a request - you just have to use the Feature Request preference.

**Comment by Wilke000** [comment]
As I told you before, create a discussions tab
