### ISSUE TITLE
no spam open boxes

### ISSUE THREAD

**Issue by cursxdforlife** [rxzyx/Blooket-Hacks#157]
pls add this feature i need to spam spooky box

**Comment by Wilke000** [comment]
Lol just look for other hacks, ik someone who has spam open but I can’t advertise it sry! And not an issue please close

**Comment by Angelio-Mustachio-Coder** [comment]
just click instant open and Spam. NOT AN ISSUE

**Comment by leo80099** [comment]
how do you do the hack's

**Comment by rxzyx** [comment]
Not an issue!

**Comment by ZackiBoiz** [comment]
Again, no issue here.
