### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SchoolLazy** [rxzyx/Blooket-Hacks#159]
i chose the rainbow astornaut and when i chose it the blook i had was a cow and its more difficult to type in the blook you

**Comment by rxzyx** [comment]
???.

**Comment by SchoolLazy** [comment]
![Screenshot 2022-11-02 10 57 45 AM](https://user-images.githubusercontent.com/116580502/199566402-025e02d0-33c6-41a2-8849-18c673dda936.png)
what i chose

**Comment by SchoolLazy** [comment]
i was testing the updated hack out and it does not work anymore

**Comment by rxzyx** [comment]
Ok. Sorry, turns out everyone complaining about the hack not working was probably a false issue, will be reverted back to original!

**Comment by ZackiBoiz** [comment]
That's weird.

**Comment by ZackiBoiz** [comment]
Did not happen when I tested

**Comment by SchoolLazy** [comment]
like it does work to type in the blook you want but it doesent show the one you chose when you game starts

**Comment by SchoolLazy** [comment]
bruh
