### ISSUE TITLE
Improper testing

### ISSUE THREAD

**Issue by Minesraft2** [rxzyx/Blooket-Hacks#16]
You failed to test Kick All and End Game, it only works if you're on the same account as the host

If you test it on a public game or have someone else host it, it won't work

edit: spelling

**Comment by rxzyx** [comment]
Sorry but I don’t have slaves.

**Comment by VillainsRule4000** [comment]
LOL, just open a guest session on Chrome or something like that.

**Comment by rxzyx** [comment]
Not that into testing a hack

**Comment by Glixxzzy** [comment]
kick all does work, you have to do it when your in the lobby

**Comment by Minesraft2** [comment]
Kick all only works when you're on the same account as the host

**Comment by Minesraft2** [comment]
You would need someone else to host on a different account to make sure it actually works

**Comment by rxzyx** [comment]
Wrong on both accounts/cases. Kick all only works when you’re on the same account as the host, and end game doesn’t “end the game” it just freezes it forever basically so everyone will get kicked out so end game works when you are playing. (You also need host for this)

**Comment by Glixxzzy** [comment]
i did test it on bestbro's livestream and kick all indeed work, only on the lobby though.
