### ISSUE TITLE
fix set damage

### ISSUE THREAD

**Issue by dragon731012** [rxzyx/Blooket-Hacks#161]
monster brawl set damage won't work for me.

**Comment by ZackiBoiz** [comment]
Not an issue. #156

**Comment by ZackiBoiz** [comment]
Will look into.

**Comment by BlooketHeck** [comment]
> monster brawl set damage won't work for me.

Could you send a screen recording as said in #156

**Comment by ZackiBoiz** [comment]
> > monster brawl set damage won't work for me.
> 
> Could you send a screen recording as said in #156

Yes, as it will help with what was going wrong. Also, if possible, record what happened in the console.

**Comment by rxzyx** [comment]
Waiting for the video.
