### ISSUE TITLE
the select any blook does not work still

### ISSUE THREAD

**Issue by musty40yearoldinmyparentsbasement** [rxzyx/Blooket-Hacks#163]
**Describe the bug**

**To Reproduce**
Run the code, if there is an error, provide a screenshot or copy the error. However, if there is no error but it doesn't work then show the url on where it was made and how you ran the code.

**Comment by ZackiBoiz** [comment]
Please add a video of you running the script #156 

Since you haven't added a clear description, I don't know what you are experiencing. I have made a pull request on changing the script however. (#162) 

This should hopefully help you.

**Comment by ZackiBoiz** [comment]
If you want the script from the pull request I made, it's [here](https://github.com/rxzyx/Blooket-Hacks/blob/b783012c30f9c69546a68eba43b5e5fe7dfa306a/Default%20Scripts/Select%20Any%20Blook.js)

**Comment by rxzyx** [comment]
> Please add a video of you running the script #156
> 
> Since you haven't added a clear description, I don't know what you are experiencing. I have made a pull request on changing the script however. (#162)
> 
> This should hopefully help you.

^
