### ISSUE TITLE
hello i would like to adress a quick thing i wish was addedd

### ISSUE THREAD

**Issue by shivie00** [rxzyx/Blooket-Hacks#164]
hello, this isn't necessarily an issue but a little fix, would it be alright if you added an auto open boxes feature? this is a feature where you type how many boxes you want to open and then auto-open it. I would love this hack
    
          cheers, shivam mohanty

**Comment by VillainsRule4000** [comment]
@rxzyx False issue.
@shivie00 Join the Discord server for suggestions.

**Comment by rxzyx** [comment]
No false issue challenge in 1 day [IMPOSSIBLE]

**Comment by VillainsRule4000** [comment]
I am going to go through all 130 issues and count the dumb ones.
