### ISSUE TITLE
Can you please make a auto open feature for blooket please please please

### ISSUE THREAD

**Issue by ItzBK29** [rxzyx/Blooket-Hacks#170]
**Describe the bug**

**To Reproduce**
Run the code, if there is an error, provide a screenshot or copy the error. However, if there is no error but it doesn't work then show the url on where it was made and how you ran the code.

**Comment by BlooketHeck** [comment]
@rxzyx False issue

**Comment by BlooketHeck** [comment]
See #156

**Comment by NathanBollard** [comment]
False issue.

**Comment by rxzyx** [comment]
False issue.
