### ISSUE TITLE
[BUG] ANTI BAN

### ISSUE THREAD

**Issue by ItzsMeAight** [rxzyx/Blooket-Hacks#172]
So i did in the search bar "javascript:" all the other scripts work fine but when i did anti ban the host kicked me and i no longer was on the leadarboard, how is it meant to work?

**Comment by NathanBollard** [comment]
> So i did in the search bar "javascript:" all the other scripts work fine but when i did anti ban the host kicked me and i no longer was on the leadarboard, how is it meant to work?

[Anti-Ban.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Anti-Ban.js) is supposed to let you play on your account even if your account is blocked or temporarily blocked.

**Comment by NathanBollard** [comment]
This issue breaks the issue rule 2.1.

**Comment by NathanBollard** [comment]
False issue.

**Comment by BlooketHeck** [comment]
False Issue

**Comment by BlooketHeck** [comment]
> False Issue

See #156

**Comment by rxzyx** [comment]
False issue.

**Comment by rxzyx** [comment]
> > So i did in the search bar "javascript:" all the other scripts work fine but when i did anti ban the host kicked me and i no longer was on the leadarboard, how is it meant to work?
> 
> [Anti-Ban.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Anti-Ban.js) is supposed to let you play on your account even if your account is blocked or temporarily blocked.

Misinformation. Anti-ban is supposed to PREVENT your account from being banned.

**Comment by chessmcface** [comment]
@rxzyx what page on blooket do you use anti-ban on?

**Comment by ZackiBoiz** [comment]
@chessmcface Any page.

**Comment by NathanBollard** [comment]
> > > So i did in the search bar "javascript:" all the other scripts work fine but when i did anti ban the host kicked me and i no longer was on the leadarboard, how is it meant to work?
> > 
> > 
> > [Anti-Ban.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Anti-Ban.js) is supposed to let you play on your account even if your account is blocked or temporarily blocked.
> 
> Misinformation. Anti-ban is supposed to PREVENT your account from being banned.

Okay.

**Comment by Wilke000** [comment]
Anti-ban is for using a hack that works but bans you

**Comment by Wilke000** [comment]
Or just keeping you safe from blooket’s api

**Comment by NathanBollard** [comment]
> @chessmcface Any page.

Not all, since there are multiple Blooket base links. It works on [play.blooket.com](https://play.blooket.com) and [dashboard.blooket.com](https://dashboard.blooket.com).

**Comment by Wilke000** [comment]
They meant any blooket page I think

**Comment by VillainsRule4000** [comment]
what the heck is rule 2.1
AntiBan operates by blocking all requests to and from the API endpoint suspend-me.
It probably doesn't work since Blooket changed their API urls.

**Comment by NathanBollard** [comment]
> what the heck is rule 2.1 AntiBan operates by blocking all requests to and from the API endpoint suspend-me. It probably doesn't work since Blooket changed their API urls.

Rule 2.1 is in #156. It says: "1. Add a link to the hack."

**Comment by VillainsRule4000** [comment]
it's not rule 2.1 lmao

**Comment by NathanBollard** [comment]
> it's not rule 2.1 lmao

Then what is it?
