### ISSUE TITLE
Set lure [BUG]

### ISSUE THREAD

**Issue by Glixxzzy** [rxzyx/Blooket-Hacks#176]
When it asks me what lure value, I type 5 but then it sets it to 4.
[Screen recording 2022-11-06 1.04.20 AM.webm](https://user-images.githubusercontent.com/108609138/200155135-d7b027e1-8f2a-4ba0-8b85-34be84e75933.webm)

**Comment by ZackiBoiz** [comment]
What?

**Comment by ZackiBoiz** [comment]
Oh, that's because you have to reduce it by 1 to get the actual lure value

**Comment by Glixxzzy** [comment]
oh
