### ISSUE TITLE
New request

### ISSUE THREAD

**Issue by addasdasdasdasdasd** [rxzyx/Blooket-Hacks#182]
There should be a command where you can simulate opening blooks from certain packs

**Comment by ZackiBoiz** [comment]
Non issue

**Comment by addasdasdasdasdasd** [comment]
where do i write the requests?

**Comment by Wilke000** [comment]
Well, I suggested he add a discussions, but he said no. If you have discord, join the discord

**Comment by addasdasdasdasdasd** [comment]
yeah, what is the discord server link

**Comment by Wilke000** [comment]
On the readme

**Comment by Wilke000** [comment]
https://discord.gg/abqMVbDanB￼
Join the rzx's modz Discord Server!
discord.gg

**Comment by BlooketHeck** [comment]
@rxzyx False issue #156

**Comment by rxzyx** [comment]
False issue.
