### ISSUE TITLE
[BUG] auto answer not working

### ISSUE THREAD

**Issue by GuytheKing777** [rxzyx/Blooket-Hacks#183]
gives an error

**Comment by BlooketHeck** [comment]
Please give a screen recording of the error. #156

**Comment by rxzyx** [comment]
Send video.

**Comment by GuytheKing777** [comment]
> 
https://www.youtube.com/watch?v=jp8NdXMbDug

**Comment by rxzyx** [comment]
I didn’t make that hack, @NathanBollard did and it appears he has done it wrong.

**Comment by VillainsRule4000** [comment]
you don't test hacks before merge?
@NathanBollard nice "friend" of yours to make the hack :D

**Comment by rxzyx** [comment]
> you don't test hacks before merge? @NathanBollard nice "friend" of yours to make the hack :D

I usually do if it's not obfuscated, but now I'll test.

**Comment by NathanBollard** [comment]
It works for me! Which gamemode(s) does it not work on?

**Comment by Wilke000** [comment]
If it’s on battle Royale it’s unhackable

**Comment by Wilke000** [comment]
Anything else it should work

**Comment by NathanBollard** [comment]
> If it’s on battle Royale it’s unhackable

Thank you for letting me know. It looks like it can't be fixed in the same hack, so it'll just have a note it [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md). Don't change anything yet though, since I haven't tested it yet. I'll reply to this message once I am done testing the hack in Battle Royale.

**Comment by NathanBollard** [comment]
> > If it’s on battle Royale it’s unhackable
> 
> Thank you for letting me know. It looks like it can't be fixed in the same hack, so it'll just have a note it [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md). Don't change anything yet though, since I haven't tested it yet. I'll reply to this message once I am done testing the hack in Battle Royale.

I tested the hack out on Battle Royale, and it seems to not work. I'm guessing it doesn't work on Classic either, but note that I haven't tested on that. I guess the best solution would be the one i suggested in https://github.com/rxzyx/Blooket-Hacks/issues/183#issuecomment-1306040707.

**Comment by VillainsRule4000** [comment]
You should, as a creator of the hack, fix it on Royale. Post an unobfuscated version here and I will patch it.
In the future, have your mystery "friend" make the PR.

**Comment by NathanBollard** [comment]
> You should, as a creator of the hack, fix it on Royale. Post an unobfuscated version here and I will patch it. In the future, have your mystery "friend" make the PR.

Why would I? It's not like there's any other hacks for Battle Royale.
