### ISSUE TITLE
flood game dosen't work

### ISSUE THREAD

**Issue by cxoio** [rxzyx/Blooket-Hacks#187]
when i run the code i do the normal stuff then it only creates 1  bot and when i redo the code it dosen't work completly 
so it only makes one bot and then stops. I even wait for 1 minute and still dosen't work.
![Screenshot (50)](https://user-images.githubusercontent.com/117413086/200457966-4226fc34-6905-4204-bc3f-8d24d48f325a.png)
![Screenshot (49)](https://user-images.githubusercontent.com/117413086/200457982-63485971-f8c1-40c4-97c3-5cff3a722556.png)
![Screenshot (48)](https://user-images.githubusercontent.com/117413086/200458002-fc894485-c7c3-407c-b9f9-38521bfacaf9.png)

**Comment by cxoio** [comment]
i have jusgt relized how to use the flooder but please and some instructions i got really confused

**Comment by ZackiBoiz** [comment]
> i have jusgt relized how to use the flooder but please and some instructions i got really confused

It should be pretty obvious... If you find it confusing, follow these instructions

1. Copy the script
2. Go to your Blooket Play tab
3. Open console and paste script
4. Enter bot amount and bot names
