### ISSUE TITLE
Custom Blooks

### ISSUE THREAD

**Issue by Wilke000** [rxzyx/Blooket-Hacks#189]
I know, i know, this isn't an issue and you will close is as soon as possible but when is the custom blooks tutorial coming out?

**Comment by Wilke000** [comment]
Well I was just wondering if you knew, you didn’t have to be sarcastic lol

**Comment by rxzyx** [comment]
Who said I was being sarcastic? ))

**Comment by ZackiBoiz** [comment]
> Yeah. Because I’m two people simultaneously and I can read minds.

p.q

**Comment by Wilke000** [comment]
Ok ty
