### ISSUE TITLE
Bug:multiple not working hacks

### ISSUE THREAD

**Issue by chessmcface** [rxzyx/Blooket-Hacks#193]
broken hacks
-all answeres correct
-anti-ban
-choose any block

**Comment by rxzyx** [comment]
False issue.

**Comment by rxzyx** [comment]
All 3 tested, works.

**Comment by VillainsRule4000** [comment]
When did you last test? @rxzyx

**Comment by rxzyx** [comment]
Like 3 days ago.

**Comment by VillainsRule4000** [comment]
Try one now, if it doesn't work, then look at all three.

**Comment by ZackiBoiz** [comment]
> broken hacks -all answeres correct -anti-ban -choose any block

They all work. Tested.

**Comment by ZackiBoiz** [comment]
@chessmcface send a video

**Comment by chessmcface** [comment]
https://user-images.githubusercontent.com/105688760/200963753-ad862833-318b-46ae-9e53-79ed24cc459f.mp4

**Comment by chessmcface** [comment]
done video uploaded above, this is the video about choose any blook
