### ISSUE TITLE
Bug: Monster brawl set damage does not work for me. 

### ISSUE THREAD

**Issue by MASTER8359** [rxzyx/Blooket-Hacks#194]
I put the code in the developer console but nothing happens. 
https://watch.screencastify.com/v/5kk7fy92srcegBueFTib

**Comment by BlooketHeck** [comment]
That is weirld

**Comment by cxoio** [comment]
its either for hosted games or just a glitch

**Comment by BlooketHeck** [comment]
Let me add @VillainsRule4000 to this

**Comment by VillainsRule4000** [comment]
it just doesn't work
@rxzyx remove Set Damage.js in monster brawl

**Comment by NathanBollard** [comment]
> it just doesn't work @rxzyx remove Set Damage.js in monster brawl

I can create a pull request for that.

**Comment by VillainsRule4000** [comment]
it doesn't work.

**Comment by ZackiBoiz** [comment]
> it doesn't work.

Yeah, it's been like that for a while 😅

**Comment by rxzyx** [comment]
Will be removed.

**Comment by NathanBollard** [comment]
#192
