### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by MrCrayfish01** [rxzyx/Blooket-Hacks#197]
How do I use manipulate plus?
it just says undefined after I input the code

**Comment by NathanBollard** [comment]
Please re-read #156.

**Comment by VillainsRule4000** [comment]
funny you say that, with all your false PRs

**Comment by ZackiBoiz** [comment]
@MrCrayfish01 you are running Manipulate Plus correctly!

This hack gives you the ability to play unreleased games, that are only available to Plus users. This hack is useless right now, but will be useful when a new gamemode comes out.

**Comment by ZackiBoiz** [comment]
> False issue.

How so?

**Comment by chessmcface** [comment]
@ZackiBoiz 
thxs for telling me really useful info!

**Comment by rxzyx** [comment]
> @MrCrayfish01 you are running Manipulate Plus correctly!
> 
> This hack gives you the ability to play unreleased games, that are only available to Plus users. This hack is useless right now, but will be useful when a new gamemode comes out.

^.

**Comment by NathanBollard** [comment]
> funny you say that, with all your false PRs

Stop.

**Comment by NathanBollard** [comment]
> lol @NathanBollard it was a joke

![dwayne johnson gif](https://user-images.githubusercontent.com/116772462/201702469-15c9ff5f-a1e6-4ebe-b39a-b2ab33f71b10.gif)

**Comment by MrCrayfish01** [comment]
> @MrCrayfish01 you are running Manipulate Plus correctly!
> 
> This hack gives you the ability to play unreleased games, that are only available to Plus users. This hack is useless right now, but will be useful when a new gamemode comes out.

Ok thanks I was confused

**Comment by NathanBollard** [comment]
> > @MrCrayfish01 you are running Manipulate Plus correctly!
> > This hack gives you the ability to play unreleased games, that are only available to Plus users. This hack is useless right now, but will be useful when a new gamemode comes out.
> 
> Ok thanks I was confused

His thanks.
