### ISSUE TITLE
New hack idea.

### ISSUE THREAD

**Issue by JaxsonLLama0216** [rxzyx/Blooket-Hacks#199]
Make a new hack to where you can use characters things your profile doesn't have  (Like the blook icon, Title, and Banner.)

Sorry if it pops up as a bug (On github) I didn't know how to change it.

**Comment by rxzyx** [comment]
False issue.

**Comment by ZackiBoiz** [comment]
> Make a new hack to where you can use characters things your profile doesn't have (Like the blook icon, Title, and Banner.)
> 
> Sorry if it pops up as a bug (On github) I didn't know how to change it.

^. This is a false issue, and the idea is improbable.

**Comment by VillainsRule4000** [comment]
Impossible*

**Comment by ZackiBoiz** [comment]
> Impossible*

yeah
