### ISSUE TITLE
Default scripts

### ISSUE THREAD

**Issue by Saber-Tooth-Tiger** [rxzyx/Blooket-Hacks#2]
rxzyx, in the default scripts, 'Select any blook' isn't working :( ANd the 'End game' only closes on ur side not on the host's side, but others are great! :) 💯 👍 Hope u could fix those 2 minor ishues up thanks!!!!!!!!!!!!!!!!!!

**Comment by rxzyx** [comment]
Ty but closed for false issue, select any Blook you have to select any random blook u have and you will unlock them, and for end game it will end the game it just won’t say “Game Ended”.
