### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by CrzyForHackz** [rxzyx/Blooket-Hacks#202]
Hi! The flood game glitch sadly isn't working!?

I don't have a screen recording but I hope this alerts some to change/check it.

https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Flood%20Game.js

**Comment by rxzyx** [comment]
Tested. Works. Will be tested again soon.

**Comment by VillainsRule4000** [comment]
It actually doesn't. Test again, @rxzyx.

**Comment by rxzyx** [comment]
> It actually doesn't. Test again, @rxzyx.

Tested. Fixed.

**Comment by CrzyForHackz** [comment]
thank you very much :)
