### ISSUE TITLE
this isnt a issue but a request 

### ISSUE THREAD

**Issue by kmanz3** [rxzyx/Blooket-Hacks#204]
**Describe the bug:if it is posiible can you guys make a improve pack luck hack so you can get free chromas

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO https://github.com/rxzyx/Blooket-Hacks/issues/156*

**Comment by Angelio-Mustachio-Coder** [comment]
False issue. Also impossible since server based.

**Comment by ZackiBoiz** [comment]
> False issue. Also impossible since server based.

^
