### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by SchoolLazy** [rxzyx/Blooket-Hacks#205]
how do i make the get all answers right work because it doesn't

**Comment by NathanBollard** [comment]
#90

**Comment by rxzyx** [comment]
False issue. Will be tested again later.

**Comment by NathanBollard** [comment]
> False issue. Will be tested again later.

Testing right now.

**Comment by NathanBollard** [comment]
> > False issue. Will be tested again later.
> 
> Testing right now.

[All Answers Correct.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/All%20Answers%20Correct.js) does not work.
Proof: [Video](https://user-images.githubusercontent.com/116772462/201735774-ffd81a2f-dc66-4e0f-9937-90c1a8972a6f.webm)

**Comment by VillainsRule4000** [comment]
alright what's the issue

**Comment by NathanBollard** [comment]
> alright what's the issue

See https://github.com/rxzyx/Blooket-Hacks/issues/205#issuecomment-1314186259.

**Comment by VitalTencelll** [comment]
> 

Coolio
