### ISSUE TITLE
Bug: Copied someones code

### ISSUE THREAD

**Issue by ThnksCJ** [rxzyx/Blooket-Hacks#206]
**Describe the bug:**
seems you copied another repos code and obf'd the code

https://github.com/rxzyx/Blooket-Hacks/blob/main/Crazy%20Kingdom/Choice%20ESP.js

```
(() => {
  if (window.location.pathname != '/kingdom') {
    return alert('You must be in a crazy kingdom game!')
  }
  let _0x33de6e = setInterval(() => {
    try {
      if (window.location.pathname != '/kingdom') {
        return clearInterval(_0x33de6e)
      }
      Array.from(document.getElementsByClassName('choiceESP')).forEach(
        (_0x1bcdf4) => _0x1bcdf4.remove()
      )
      let _0x1ce34b = {
          materials: Array.from(document.querySelectorAll('div')).find(
            (_0x44fa03) =>
              Array.from(_0x44fa03.children).find((_0x51769e) =>
                _0x51769e.className.includes('tree')
              )
          ),
          people: Array.from(document.querySelectorAll('div')).find(
            (_0x3007b6) =>
              Array.from(_0x3007b6.children).find(
                (_0x343d6b) =>
                  _0x343d6b.className.includes('users') &&
                  _0x343d6b.parentElement.className.includes('statContainer')
              )
          ),
          happiness: Array.from(document.querySelectorAll('div')).find(
            (_0x305a1f) =>
              Array.from(_0x305a1f.children).find((_0x4096e1) =>
                _0x4096e1.className.includes('grin')
              )
          ),
          gold: Array.from(document.querySelectorAll('div')).find((_0x411510) =>
            Array.from(_0x411510.children).find((_0x185b3c) =>
              _0x185b3c.className.includes('coins')
            )
          ),
        },
        _0x26f46c = Object.values(document.querySelector('#app > div > div'))[1]
          .children[1]['_owner'].stateNode.state.guest
      Object.entries(_0x26f46c.yes).forEach((_0x37a32b) => {
        if (_0x37a32b[0] == 'msg') {
          return
        }
        let _0x2e91ba = document.createElement('div')
        _0x2e91ba.className = 'choiceESP'
        _0x2e91ba.style =
          'font-size: 24px; color: rgb(75, 194, 46); font-weight: bolder;'
        _0x2e91ba.innerText = String(_0x37a32b[1])
        _0x1ce34b[_0x37a32b[0]].appendChild(_0x2e91ba)
      })
      Object.entries(_0x26f46c.no).forEach((_0x5f5c29) => {
        if (_0x5f5c29[0] == 'msg') {
          return
        }
        let _0x144cf0 = document.createElement('div')
        _0x144cf0.className = 'choiceESP'
        _0x144cf0.style =
          'font-size: 24px; color: darkred; font-weight: bolder;'
        _0x144cf0.innerText = String(_0x5f5c29[1])
        _0x1ce34b[_0x5f5c29[0]].appendChild(_0x144cf0)
      })
    } catch (_0x90e9b1) {}
  }, 0)
  if (
    confirm('This code is from a github repository, do you want to see it?')
  ) {
    window.open('https://github.com/glixzzy/blooket-hack', '_blank')
  }
})()
```

^^ the code deobfuscated

**Comment by NathanBollard** [comment]
False issue.

**Comment by ZackiBoiz** [comment]
> **Describe the bug:** seems you copied another repos code and obf'd the code
> 
> https://github.com/rxzyx/Blooket-Hacks/blob/main/Crazy%20Kingdom/Choice%20ESP.js
> 
> ```
> (() => {
>   if (window.location.pathname != '/kingdom') {
>     return alert('You must be in a crazy kingdom game!')
>   }
>   let _0x33de6e = setInterval(() => {
>     try {
>       if (window.location.pathname != '/kingdom') {
>         return clearInterval(_0x33de6e)
>       }
>       Array.from(document.getElementsByClassName('choiceESP')).forEach(
>         (_0x1bcdf4) => _0x1bcdf4.remove()
>       )
>       let _0x1ce34b = {
>           materials: Array.from(document.querySelectorAll('div')).find(
>             (_0x44fa03) =>
>               Array.from(_0x44fa03.children).find((_0x51769e) =>
>                 _0x51769e.className.includes('tree')
>               )
>           ),
>           people: Array.from(document.querySelectorAll('div')).find(
>             (_0x3007b6) =>
>               Array.from(_0x3007b6.children).find(
>                 (_0x343d6b) =>
>                   _0x343d6b.className.includes('users') &&
>                   _0x343d6b.parentElement.className.includes('statContainer')
>               )
>           ),
>           happiness: Array.from(document.querySelectorAll('div')).find(
>             (_0x305a1f) =>
>               Array.from(_0x305a1f.children).find((_0x4096e1) =>
>                 _0x4096e1.className.includes('grin')
>               )
>           ),
>           gold: Array.from(document.querySelectorAll('div')).find((_0x411510) =>
>             Array.from(_0x411510.children).find((_0x185b3c) =>
>               _0x185b3c.className.includes('coins')
>             )
>           ),
>         },
>         _0x26f46c = Object.values(document.querySelector('#app > div > div'))[1]
>           .children[1]['_owner'].stateNode.state.guest
>       Object.entries(_0x26f46c.yes).forEach((_0x37a32b) => {
>         if (_0x37a32b[0] == 'msg') {
>           return
>         }
>         let _0x2e91ba = document.createElement('div')
>         _0x2e91ba.className = 'choiceESP'
>         _0x2e91ba.style =
>           'font-size: 24px; color: rgb(75, 194, 46); font-weight: bolder;'
>         _0x2e91ba.innerText = String(_0x37a32b[1])
>         _0x1ce34b[_0x37a32b[0]].appendChild(_0x2e91ba)
>       })
>       Object.entries(_0x26f46c.no).forEach((_0x5f5c29) => {
>         if (_0x5f5c29[0] == 'msg') {
>           return
>         }
>         let _0x144cf0 = document.createElement('div')
>         _0x144cf0.className = 'choiceESP'
>         _0x144cf0.style =
>           'font-size: 24px; color: darkred; font-weight: bolder;'
>         _0x144cf0.innerText = String(_0x5f5c29[1])
>         _0x1ce34b[_0x5f5c29[0]].appendChild(_0x144cf0)
>       })
>     } catch (_0x90e9b1) {}
>   }, 0)
>   if (
>     confirm('This code is from a github repository, do you want to see it?')
>   ) {
>     window.open('https://github.com/glixzzy/blooket-hack', '_blank')
>   }
> })()
> ```
> 
> ^^ the code deobfuscated

This hack from glixzzy doesn't work.

**Comment by ThnksCJ** [comment]
It did, but still I didn't see any credit to him + why obf a file that he didn't obf

**Comment by Angelio-Mustachio-Coder** [comment]
From who?

**Comment by rxzyx** [comment]
I didn't make that file.
Rest assured, I will talk with @ZackiBoiz about this.

**Comment by rxzyx** [comment]
And no response. Don't falsely accuse.

**Comment by VillainsRule4000** [comment]
:rofl: some people these days
even if @ZackiBoiz DID take it from gliz, oh well like who cares
at least he made it work
