### ISSUE TITLE
Improper Filenames

### ISSUE THREAD

**Issue by VillainsRule4000** [rxzyx/Blooket-Hacks#208]
If I download the repo, many code editors don't recognize it properly, as folder and file names have spaces.
There are a few options for this:
1. Use dashes (ie `Fishing-Frenzy/Set-Weight.js`)
2. Just remove spaces (ie `FishingFrenzy/SetWeight.js`)
3. Use Blooket's one-word names for games and standard file naming (ie `fishing/setWeight.js`)
4. Keep it the way it is

I could make one mass commit in a PR. Just lmk what you decide.

**Comment by rxzyx** [comment]
"I could make one mass commit in a PR. Just lmk what you decide."

Dashes would be fine.

**Comment by VillainsRule4000** [comment]
Do you know how to put them into all one commit?
I will.

**Comment by NathanBollard** [comment]
> Do you know how to put them into all one commit? I will.

I already finished. See #211.

**Comment by NathanBollard** [comment]
False issue.

**Comment by VillainsRule4000** [comment]
You go to FALSE ISSUE? :rofl: it's not.

**Comment by NathanBollard** [comment]
> You go to FALSE ISSUE? 🤣 it's not.

Again, see #156.

**Comment by VillainsRule4000** [comment]
> 

pls re-read #156, ty
