### ISSUE TITLE
Bug: Tower of Doom Set Health not working

### ISSUE THREAD

**Issue by VillainsRule4000** [rxzyx/Blooket-Hacks#210]
**Describe the bug:** 
When I use Tower of Doom Set Health with the Bookmarklet method, it does not set my health.

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by VillainsRule4000** [comment]
example issue for #156

**Comment by rxzyx** [comment]
Oh, example.

**Comment by NathanBollard** [comment]
How is this an example? This doesn't follow:
> 1. Add a link to the hack.

**Comment by VillainsRule4000** [comment]
hush

**Comment by NathanBollard** [comment]
> hush

?

**Comment by ZackiBoiz** [comment]
> > hush
> 
> ?

*add a link to the hack*

**Comment by VillainsRule4000** [comment]
> > > hush
> > 
> > 
> > ?
> 
> _add a link to the hack_

I updated the guidelines. Reread
