### ISSUE TITLE
Someone is plagiarizing your work.

### ISSUE THREAD

**Issue by Jude-Gideon** [rxzyx/Blooket-Hacks#216]
https://github.com/Doomlands/blookethack if you look at the obfuscation it's identical.

**Comment by rxzyx** [comment]
Thanks.

**Comment by Jude-Gideon** [comment]
> Thanks.

No problem, I'd recommend making your own license so you can have full control over everything, just a recommendation though, it's sad when people steal code.

**Comment by Jude-Gideon** [comment]
> remove



> All licenses have the ability for people to copy. Do I just remove my License so nobody can take anything?

Look at [this license](https://github.com/Jude-Gideon/Blooket/blob/main/LICENSE) I custom made it and it gives no right to any copying without direct permission from me etc, I can let you use it if you want, let me know and I'll add you to the list if you're interested.

**Comment by rxzyx** [comment]
Thanks. That vacuous geezer made me realise that I can make my own license.

**Comment by rxzyx** [comment]
I'll make my own - and yeah ... the support team asks a billion questions before accepting any DMCA.

**Comment by Jude-Gideon** [comment]
FR, theres a difference between open source, and something you want used.

**Comment by VillainsRule4000** [comment]
yes.

**Comment by VillainsRule4000** [comment]
> Yeah, I can add you to mine if you would like, or just make your own, I had to do that after no other license covered my code. Github really needs to update licenses for developers who want their code usable, but not open source.

It's something for open source, but especially on games where the average user is <10, you need a special kind of thing.

**Comment by Jude-Gideon** [comment]
> > Yeah, I can add you to mine if you would like, or just make your own, I had to do that after no other license covered my code. Github really needs to update licenses for developers who want their code usable, but not open source.
> 
> It's something for open source, but especially on games where the average user is <10, you need a special kind of thing.

FR. People are like "just go open source or private" I want my code usable, not editable thought.

**Comment by VillainsRule4000** [comment]
> > > Yeah, I can add you to mine if you would like, or just make your own, I had to do that after no other license covered my code. Github really needs to update licenses for developers who want their code usable, but not open source.
> > 
> > 
> > It's something for open source, but especially on games where the average user is <10, you need a special kind of thing.
> 
> FR. People are like "just go open source or private" I want my code usable, not editable thought.

Right. Many people steal without credit. Even if you do credit, why steal lol.

**Comment by NathanBollard** [comment]
:|
