### ISSUE TITLE
Please add battle royale hacks

### ISSUE THREAD

**Issue by 1010101010101ww** [rxzyx/Blooket-Hacks#217]
**Describe the bug: this isn't a bug this a hack request, can you please add battle royale hacks

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by VillainsRule4000** [comment]
no hack requests.
not possible as well.
close.

**Comment by BlooketHeck** [comment]
@rxzyx Close false issue

**Comment by ZackiBoiz** [comment]
> no hack requests. not possible as well. close.

Put suggestions in the Discord server.

**Comment by NathanBollard** [comment]
False issue, see #156. Please close this issue as completed.

**Comment by rxzyx** [comment]
False issue.
