### ISSUE TITLE
[Not An Issue]

### ISSUE THREAD

**Issue by NathanBollard** [rxzyx/Blooket-Hacks#218]
@rxzyx, why do you have a branch called [add-code-of-conduct-1](https://github.com/rxzyx/Blooket-Hacks/tree/add-code-of-conduct-1)? It's useless, and hasn't been updated since October 10, 2022. Should it be deleted? You already have [CODE_OF_CONDUCT.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/CODE_OF_CONDUCT.md).

**Comment by NathanBollard** [comment]
#156

**Comment by rxzyx** [comment]
K.
