### ISSUE TITLE
Bug: Manipulate Plus not working

### ISSUE THREAD

**Issue by ColeCat119** [rxzyx/Blooket-Hacks#221]
**Describe the bug:**
I try to use it, but nothing pops up.

**Screen recording:**
can't sorry

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by Floragato** [comment]
uh, manipulate plus is used for unlocking plus gamemodes. there are no gamemodes to unlock right now, so it "doesn't work".

**Comment by VillainsRule4000** [comment]
yes.

**Comment by rxzyx** [comment]
False issue.

**Comment by NathanBollard** [comment]
False issue.

**Comment by ZackiBoiz** [comment]
It does work, but there is no use for it right now.

**Comment by ItzBK29** [comment]
It will not let you copy sets

**Comment by NathanBollard** [comment]
> It will not let you copy sets

So?

**Comment by NathanBollard** [comment]
> can somone make a script for that please? copy sets

No. Just get Plus.
