### ISSUE TITLE
Yo you might wannna DMCA now

### ISSUE THREAD

**Issue by Jude-Gideon** [rxzyx/Blooket-Hacks#222]
If you haven't I would go ahead, he responded earlier with just a skull emoji I don't think he plans to take them down.

**Comment by Jude-Gideon** [comment]
Also this kid is stealing your work https://github.com/P-DennyGamingYT/Blooket-Hacks

even though he says its your you can still DMCA cause you didn't give him permission.

**Comment by P-DennyGamingYT** [comment]
I don’t need permission. He has no copyright except for MIT. I can still share and edit but I have to give credit. Which I did. I am literally just making a collection of every hack from every user I can find.

**Comment by VillainsRule4000** [comment]
The License has been updated.

**Comment by P-DennyGamingYT** [comment]
Ok go ahead and try and Dmca me with no real copyright proof!

**Comment by P-DennyGamingYT** [comment]
Sorry for making a collection of Blooket hacks

**Comment by VillainsRule4000** [comment]
No real copyright proof?

**Comment by rxzyx** [comment]
Actually you violated the License, @P-DennyGamingYT, if it’s not removed within a couple of hours using the terms of the license I will be forced to take action.

**Comment by P-DennyGamingYT** [comment]
You can’t do anything unless you have copyright registration.

**Comment by P-DennyGamingYT** [comment]
I legally don’t have to do anything if you have no copyright registration papers to show me

**Comment by P-DennyGamingYT** [comment]
It is also a federal crime to order a DMCA takedown based ff unregistered copyright

**Comment by Jude-Gideon** [comment]
Dawg you're retarded

**Comment by Jude-Gideon** [comment]
Dawg, he has everything he needs to DMCA you just comply with him it's not hard.

**Comment by Jude-Gideon** [comment]
> Sorry for making a collection of Blooket hacks

Theres no point.. people go to the original, you're just trying to be special my guy.

**Comment by NathanBollard** [comment]
Get BURNED

**Comment by Jude-Gideon** [comment]
lmao

**Comment by rxzyx** [comment]
> You can’t do anything unless you have copyright registration.

Sorry Johnny Law, but you actually can (I did before, that’s why licenses are a thing!)

**Comment by P-DennyGamingYT** [comment]
Ok go ahead Dmca me. Have fun!

**Comment by Hankypoo7** [comment]
Guys, this is fking blooket hacks. It does. Not. Matter.

**Comment by VillainsRule4000** [comment]
> Guys, this is fking blooket hacks. It does. Not. Matter.

People spend time making scripts. It does. Good script makers will know.

**Comment by prndndndndnndnd** [comment]
bro jude you are so annyoing take this down take this down bro will it ever matter

**Comment by prndndndndnndnd** [comment]
and you are reaally annoying

**Comment by Jude-Gideon** [comment]
> bro jude you are so annyoing take this down take this down bro will it ever matter



> and you are reaally annoying

you take time to go through all the issues i made and comment, its against my license and others to copy code lmao
