### ISSUE TITLE
Bug: Blooket Flood does not work

### ISSUE THREAD

**Issue by weasers** [rxzyx/Blooket-Hacks#223]
**Describe the bug:**
When I click the bookmark is asks for the name and then the number I want. When I check back on the host screen nothing has happened

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by peepoostpin** [comment]
ye

**Comment by ZackiBoiz** [comment]
It does work. It just takes a bit

**Comment by NathanBollard** [comment]
False issue, test again.

**Comment by rxzyx** [comment]
False issue. Works.
