### ISSUE TITLE
How do/what is an ID for custom blooks? I want my blook to be maxed out. Help?

### ISSUE THREAD

**Issue by cupcake2048** [rxzyx/Blooket-Hacks#224]
I just want to know the custom ID that gets the custom blook to be maxed out, and I want the blook to have the first white skin also. 

![Screenshot 2022-11-18 4 54 23 PM](https://user-images.githubusercontent.com/101189451/202809649-6a768757-3c89-450f-a3f2-89470fb88027.png)

So yeah can you do that also sorry if this is a bit weird but have you figured out how to bypass the cap for infinite coins or infinite XP? oh yeah and also do you know if you can give yourself blooks??? I know that's a lot to ask but when you do if you decide to respond!! thanks!

**Comment by Wilke000** [comment]
Infinite coins/xp is impossible
They are server sided

**Comment by rxzyx** [comment]
^ False issue. Also there’s a file called Custom Blooks.js
