### ISSUE TITLE
Infinite Tokens Might Work.

### ISSUE THREAD

**Issue by NathanBollard** [rxzyx/Blooket-Hacks#225]
(That I know of), there is one way to get Tokens even after you reach the daily limit: Selling Blooks. (If there is more, let me know.) Obviously, you can't get all the Blooks forever in a hack, but you get Blooks by opening packs. Do you think there's a way to set the price of any packs?

**Comment by rxzyx** [comment]
Not possible.

**Comment by ZackiBoiz** [comment]
^

**Comment by NathanBollard** [comment]
What about the rarity of the Blooks?
