### ISSUE TITLE
Host not working, in the defult scripts

### ISSUE THREAD

**Issue by RaynerBoniacio** [rxzyx/Blooket-Hacks#228]
hi, everything is good except for the kick player, end game, and kick all. Which is unfortunete, hopefully you read this and you can somewhat fix it please. But overall it was good!

**Comment by rxzyx** [comment]
By using these hacks I expect the function to read the hack. __HOST__

**Comment by rxzyx** [comment]
__HOST__ means that it’s exclusive to hosts only.

**Comment by RaynerBoniacio** [comment]
ohhhhhhh, lol, sry. But how about the anti ban? I don't think it's working
aswell

**Comment by Wilke000** [comment]
Anti ban doesn’t unaban you, only prevents you from being banned if you are using a hack that gets you banned but still works
