### ISSUE TITLE
Bug: The manipulate plus does not work at all I have tried everything and it will not work please fix this it would help so much Thx and have a nice day.

### ISSUE THREAD

**Issue by ItzBK29** [rxzyx/Blooket-Hacks#232]
**Describe the bug:**

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by rxzyx** [comment]
False issue.

**Comment by ZackiBoiz** [comment]
@ItzBK29 The hack DOES indeed work, look at issue #221
