### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by moo132** [rxzyx/Blooket-Hacks#235]
**Describe the bug:** The max tokens and XP is not working #156 

**Screen recording:** 

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by Angelio-Mustachio-Coder** [comment]
False issue. just tested, it works.

**Comment by Jude-Gideon** [comment]
False issue, just your daily cap.

**Comment by jimjamgithub** [comment]
just close this issue moo132
