### ISSUE TITLE
blooket hack

### ISSUE THREAD

**Issue by 000Oscar000** [rxzyx/Blooket-Hacks#236]
hey, this isn't exactly an issue because your code is amazing but I was wondering if you could attempt to make a code for the blooket market that allows the user to spam open packs so we don't spend so much time opening them or maybe something to boost the luck of getting something really from the packs please and thankyou

**Comment by NathanBollard** [comment]
False issue, see #156.

**Comment by rxzyx** [comment]
False issue.

**Comment by VillainsRule4000** [comment]
@rxzyx you've gotten so many requests, make one!

**Comment by VillainsRule4000** [comment]
also luck boost is impossible

**Comment by NathanBollard** [comment]
> @rxzyx you've gotten so many requests, make one!

How about you make one? You told me you code.
