### ISSUE TITLE
Bug: Manipulate plus dosen't work

### ISSUE THREAD

**Issue by ItzBK29** [rxzyx/Blooket-Hacks#238]
**Describe the bug:**

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by ZackiBoiz** [comment]
It does work, read #221

**Comment by NathanBollard** [comment]
False issue.

**Comment by rxzyx** [comment]
False issue.
