### ISSUE TITLE
the get any blook and the plus one dont work

### ISSUE THREAD

**Issue by SolarCelery** [rxzyx/Blooket-Hacks#24]

**Comment by ZackiBoiz** [comment]
Yes, about the Manipulate Plus... There seems to be nothing that happens when you run the script!

**Comment by Hyyped** [comment]
Accesses plus only gamemodes, nothing else (monster brawl) currently

**Comment by rxzyx** [comment]
> Accesses plus only gamemodes, nothing else (monster brawl) currently

Yes

**Comment by ZackiBoiz** [comment]
> > Accesses plus only gamemodes, nothing else (monster brawl) currently
> 
> Yes

It doesn't seem to work for me though...

**Comment by ZackiBoiz** [comment]
How would I use it? Can you give an example?

Thanks :)

**Comment by rxzyx** [comment]
Sorry Zack for the inconvenience, I will provide a simple explanation.

Once you have the file (Default Scripts/Manipulate Plus.js)
Click raw and ctrl + a and then ctrl + c

Now go to blooket and create a game
Once it shows the “select mode” area, run the script (Ctrl + shift + J, ctrl + v)
Now you can select the new game-mode “Monster Brawl”
I hope this helped.

**Comment by ZackiBoiz** [comment]
Sorry for responding late. Would this work in a bookmarklet? Because if so, it doesn't seem to do anything. 

Thanks for your explanation! :)

**Comment by Hyyped** [comment]
Yea it would
