### ISSUE TITLE
How to get blook code for Blooket-Hacks/Default-Scripts/Custom-Blooks.js ?

### ISSUE THREAD

**Issue by RadioactivePotato** [rxzyx/Blooket-Hacks#244]

**Comment by NathanBollard** [comment]
How do you find the number values, @ZackiBoiz?

**Comment by rxzyx** [comment]
False issue

**Comment by NathanBollard** [comment]
False issue.

**Comment by ZackiBoiz** [comment]
> How do you find the number values, @ZackiBoiz?
@NathanBollard 

Let's say you want to change the "item" value.
The number value depends on what "item" you chose.
For example, the first "item" has a value of 0, the second has a value of 1, the third with 2, and so on...

**Comment by NathanBollard** [comment]
> > How do you find the number values, @ZackiBoiz?
> > @NathanBollard
> 
> Let's say you want to change the "item" value. The number value depends on what "item" you chose. For example, the first "item" has a value of 0, the second has a value of 1, the third with 2, and so on...

There should be a list of all the IDs on a Google Doc or something, at least for the people who don't have every accessory in the game.

**Comment by ZackiBoiz** [comment]
> > > How do you find the number values, @ZackiBoiz?
> > > @NathanBollard
> > 
> > 
> > Let's say you want to change the "item" value. The number value depends on what "item" you chose. For example, the first "item" has a value of 0, the second has a value of 1, the third with 2, and so on...
> 
> There should be a list of all the IDs on a Google Doc or something, at least for the people who don't have every accessory in the game.

Ok, I'll think about that.
