### ISSUE TITLE
Chest-ESP.js

### ISSUE THREAD

**Issue by NathanBollard** [rxzyx/Blooket-Hacks#246]
Chest-ESP.js does show what's behind the chests, but the interactive choices says there's no other players to interact with, and freezes your gold and placement on the host's leaderboard.

**Comment by ZackiBoiz** [comment]
Just tested, it works fine.

**Comment by NathanBollard** [comment]
> Just tested, it works fine.

Well when I tested, I also used Flood-Game.js. Maybe that conflicted?

**Comment by NathanBollard** [comment]
> Just tested, it works fine.

Oh. I guess it just conflicted with Flood-Game.js. Sorry!
