### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by JuggyHucklebuck** [rxzyx/Blooket-Hacks#248]
Manipulate Plus isn't working and I'm not sure if the problem is where I am supposed to put it or not. I do use Javascript.

**Screen recording:**-------I can't screen record on my Chromebook.

**Comment by Wilke000** [comment]
Use Loom to screen record

**Comment by JuggyHucklebuck** [comment]
heres the vid https://www.loom.com/share/a5b5450fd0ce454ea89cb773a53ba756

**Comment by VillainsRule4000** [comment]
I'll look into it, I'm on mobile atm (so I can't do anything). Meanwhile, @Minesraft2 has a working Unlock Limited Gamemodes script.

**Comment by Wilke000** [comment]
He already has an unlock plus...

**Comment by Wilke000** [comment]
And he already has a unlock game mode script

**Comment by JuggyHucklebuck** [comment]
Thank y'all so much🙏

**Comment by Wilke000** [comment]
Np :)

**Comment by ZackiBoiz** [comment]
@JuggyHucklebuck tested, it works

**Comment by rxzyx** [comment]
False issue
