### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by AloGames69** [rxzyx/Blooket-Hacks#249]
when i do it, i know im doing it right then i click on something that requires plus, it brings me to the page asking me to but plus in blooket.

**Comment by JuggyHucklebuck** [comment]
Bro i literally commented this like an hour ago

**Comment by AloGames69** [comment]
> Bro i literally commented this like an hour ago

how was i supposed to know

**Comment by ZackiBoiz** [comment]
> > Bro i literally commented this like an hour again
> > okay.... and

Read the previous issues!! #248 it's been solved! Don't make issues that are duplicates, you might find what you are looking for in another issue.

**Comment by rxzyx** [comment]
False issue
