### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Kyoto114** [rxzyx/Blooket-Hacks#250]
None of the blooket hacks work on Chromebook. I tried recent versions but none of them work? It works on pc fine.

**Comment by Wilke000** [comment]
Probably a school setting

**Comment by ZackiBoiz** [comment]
> None of the blooket hacks work on Chromebook. I tried recent versions but none of them work? It works on pc fine.

Your county/administrator might of blocked bookmarklets :-(

**Comment by Wilke000** [comment]
That’s what I said

**Comment by Kyoto114** [comment]
That may be true

**Comment by Kyoto114** [comment]
hm, works on school pc's... It may just be with the school chromebooks then. Thank you.

**Comment by Wilke000** [comment]
Np :)

**Comment by rxzyx** [comment]
False issue
