### ISSUE TITLE
Set Damage In Tower Defense Doesn't Work

### ISSUE THREAD

**Issue by AloGames69** [rxzyx/Blooket-Hacks#251]
when you use the set damage hack in tower defense it doesn't work

**Comment by Angelio-Mustachio-Coder** [comment]
False issue.

**Comment by AloGames69** [comment]
proof https://vimeo.com/manage/videos/777458258/privacy

**Comment by ZackiBoiz** [comment]
> proof https://vimeo.com/manage/videos/777458258/privacy

It hasn't worked for a while

**Comment by ZackiBoiz** [comment]
You might need to upgrade an ability after you use the hack, I don't fully remember

**Comment by rxzyx** [comment]
False issue.
