### ISSUE TITLE
Code is easy to see from the servers

### ISSUE THREAD

**Issue by NOAHBENJ** [rxzyx/Blooket-Hacks#252]
**Describe the bug:**
The code gets uploaded to the Blooket servers, promoting the chance of a ban

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by Angelio-Mustachio-Coder** [comment]
use anti-ban. simple fix. False issue.

**Comment by rxzyx** [comment]
^. Also wdym by 'uploaded' xd - you watched the Matrix too much? The operator won't single-handedly check for things like this.
