### ISSUE TITLE
Add tokens and max xp doesnt work

### ISSUE THREAD

**Issue by Randomaccount5466** [rxzyx/Blooket-Hacks#253]
**Describe the bug:**when i go to blooket.com/play it says tokens and xp added but in reality it did not give me tokens and xp

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by Angelio-Mustachio-Coder** [comment]
False issue, close it.

**Comment by rxzyx** [comment]
False issue

**Comment by battleaxe20100** [comment]
u need to give me 50,000 coins like it was promised please im begging i
dont know how to do it just please today has sucked just please im begging

**Comment by battleaxe20100** [comment]
u need to give my son what he wanted and needed hes gets bullied caous =e
he doisnt have whatever its called coins and u better git him the 50,000
coins

**Comment by VillainsRule4000** [comment]
not 50k lol
