### ISSUE TITLE
Bug: Manipulate Plus

### ISSUE THREAD

**Issue by cupcake2048** [rxzyx/Blooket-Hacks#254]
**Describe the bug:**
I used it on the first plus game mode and it didn't work

**Screen recording:**
[Screen recording 2022-12-06 9.24.46 AM.webm](https://user-images.githubusercontent.com/101189451/205938291-d90c8612-9aa7-44c2-93d3-5ae696884e74.webm)

**Comment by cupcake2048** [comment]
i don't think so

**Comment by ZackiBoiz** [comment]
> i don't think so

Make sure it's not. lol

**Comment by VillainsRule4000** [comment]
https://github.com/Minesraft2/Blooket-Cheats has working stuff

**Comment by 106shoplol** [comment]
its not working for me either and i did the right script and right version

**Comment by rxzyx** [comment]
Should work.

**Comment by rxzyx** [comment]
@VillainsRule4000 stop promoting things

**Comment by Wilke000** [comment]
He’s just promoting hacks that are 100x better than yours and the creator doesn’t say “False issue” and closes it even if it really doesn’t work
