### ISSUE TITLE
Blooket has patched the hacks!

### ISSUE THREAD

**Issue by Educational-hacker** [rxzyx/Blooket-Hacks#257]
When you use the hacks, they don't work. There is no response window and no visual conformation of the hacks working.

Please look into this as it is a big problem for kids like me!

**Comment by Educational-hacker** [comment]
O yeah and thanks to RXZYX

**Comment by Educational-hacker** [comment]
AND all the contributers
i am following u all :)

**Comment by VillainsRule4000** [comment]
> When you use the hacks, they don't work. There is no response window and no visual conformation of the hacks working.
> 
> Please look into this as it is a big problem for kids like me!

I assume you are 13+?

**Comment by Educational-hacker** [comment]
yes indeed

**Comment by VillainsRule4000** [comment]
> yes indeed

13+ is not "kids" LMFAO

**Comment by Educational-hacker** [comment]
i guess but like i dont give a crap

**Comment by Educational-hacker** [comment]
my class is kinda annoyed tht they got patched

**Comment by Educational-hacker** [comment]
so i thought i would let u know
yk what i mean

**Comment by VillainsRule4000** [comment]
> my class is kinda annoyed tht they got patched

bro legit you're using the wrong hacks
use @Minesraft2's

**Comment by VillainsRule4000** [comment]
https://github.com/Minesraft2/Blooket-Cheats <-- these work

**Comment by Educational-hacker** [comment]
these worked 2 weeks ago for som reason

**Comment by Wilke000** [comment]
Yea Villains is right ryx’s hacks aren’t good. Minesraft’s cheats are the best

**Comment by VillainsRule4000** [comment]
> Yea Villains is right ryx’s hacks aren’t good. Minesraft’s cheats are the best

this is the only thing we have agreed on!

**Comment by Wilke000** [comment]
Lol ikr

**Comment by Educational-hacker** [comment]
haha lol

**Comment by Wilke000** [comment]
Villains and I have argued a lot if ur wondering why they said that

**Comment by Educational-hacker** [comment]
i cant use those at school with my class

**Comment by Educational-hacker** [comment]
minesraft is HTML, and inspect menu is blocked at school
only way we used them is by typing in the search bar "javascript:(hack code pasted here)

**Comment by Minesraft2** [comment]
my cheats aren't html, there's just a huge bookmark importable file in there

**Comment by Educational-hacker** [comment]
oh ok

**Comment by Wilke000** [comment]
Yea it’s just a huge bookmarklet file, download that, import it, and use it

**Comment by Angelio-Mustachio-Coder** [comment]
Mine still work

**Comment by Wilke000** [comment]
Your's it a literal fork from ryx's

**Comment by VillainsRule4000** [comment]
> Your's it a literal fork from ryx's

LMAO
bro hasn't even pushed the latest changes
I cannot with filthy skids

**Comment by rxzyx** [comment]
Looked false.

**Comment by rxzyx** [comment]
Looks*

**Comment by rxzyx** [comment]
Sad attempt of advertising, I just tested - they work.
