### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by D-da-hacker** [rxzyx/Blooket-Hacks#260]
**Describe the bug:**
This is actually a suggestion, but could you make a mystical and chroma pack. Also muliputive plus aint work.

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by VillainsRule4000** [comment]
Bro calls himself a hacker with no repos, joined 2 days ago.
You can't make a Chroma pack, LMFAO, if you could do that blooket's domain would be changed to something like gayclowns.com
read the rules, it says to join the discord for suggestions

**Comment by Wilke000** [comment]
Lol

**Comment by rxzyx** [comment]
False issue.
