### ISSUE TITLE
Cannot Get the Unban script or the tampermonkey version to work

### ISSUE THREAD

**Issue by sakopotato** [rxzyx/Blooket-Hacks#261]
Hello,
I have tried to use the anit-ban scripts but I cannot get them to work using the console or javascript:[code]. Can someone provide a detailed expanation showing how to use it?

**Comment by Wilke000** [comment]
They don’t unban they prevent you from being banned in the 1st place. Example if you were using an old hack that still worked but gets you banned

**Comment by rxzyx** [comment]
^
