### ISSUE TITLE
Maybe some extra directions on what page on Blooket to go to and what to do? Thanks for reading. [REQUEST]

### ISSUE THREAD

**Issue by TheOGLSS** [rxzyx/Blooket-Hacks#268]
**Describe the feature you want:**
e.g. I want [a feature] for [gamemode]

**Why do you want this feature?**
e.g. It makes the game way easier!

**How will this improve your way of playing?**
e.g. I will use it alot!

**Comment by TheOGLSS** [comment]
eggs

**Comment by TheOGLSS** [comment]
wertyuiopoiuytrewwertyuioppoiuytrewwertyuioiuytrewqwertyuiopqwertyuiopasdfghjklzxcvbnmabcdefghijklmnopqrstubwxyz

**Comment by FortniteBattlePass** [comment]
can I make the Chanse of getting a legendry blook better?

**Comment by ZackiBoiz** [comment]
> wertyuiopoiuytrewwertyuioppoiuytrewwertyuioiuytrewqwertyuiopqwertyuiopasdfghjklzxcvbnmabcdefghijklmnopqrstubwxyz

💀

**Comment by rxzyx** [comment]
...
