### ISSUE TITLE
can I make the Chanse of getting a legendry better? [REQUEST]

### ISSUE THREAD

**Issue by FortniteBattlePass** [rxzyx/Blooket-Hacks#270]
**Describe the feature you want:**
e.g. I want [a feature] for [gamemode]

**Why do you want this feature?**
e.g. It makes the game way easier!

**How will this improve your way of playing?**
e.g. I will use it alot!

**Comment by CrypticLucid** [comment]
no

**Comment by ZackiBoiz** [comment]
not possible

**Comment by Wilke000** [comment]
Lol yea everything like changing the token limit, the box chance, the token reset limit, that’s all server based

**Comment by rxzyx** [comment]
^
