### ISSUE TITLE
lliamii open this right neow

### ISSUE THREAD

**Issue by mungK11** [rxzyx/Blooket-Hacks#272]
give me roux and make a custom bloket for mie

**Comment by mungK11** [comment]
plzplszplszplszplzplzplzplzplz

**Comment by Wilke000** [comment]
Don’t we all want a robux hack 😂

**Comment by Angelio-Mustachio-Coder** [comment]
idiot. False issue.

**Comment by mungK11** [comment]
where is liamii

**Comment by mungK11** [comment]
> 

and no you idoit it is a issue because i payed him and he better give me t h e custom blok i ordeard

**Comment by VillainsRule4000** [comment]
> and no you idoit it is a issue because i payed him and he better give me t h e custom blok i ordeard

you can't get a custom blook in blooket. :skull: bro got scammed hard. it's impossible to add custom blooks to the game.

**Comment by ZackiBoiz** [comment]
> > and no you idoit it is a issue because i payed him and he better give me t h e custom blok i ordeard
> 
> you can't get a custom blook in blooket. 💀 bro got scammed hard. it's impossible to add custom blooks to the game.

Bro asked for Party Pig V2

**Comment by AmongUsSusman** [comment]
Brobama
![download](https://user-images.githubusercontent.com/120415598/207329902-a3a14f57-746f-473b-a59a-b158b998db22.jpeg)

**Comment by cucumber25** [comment]
Fortnite battle pass

**Comment by cucumber25** [comment]
blooketeejekrwnfjvc34mtkj h,m.hybiukjltr

**Comment by cucumber25** [comment]
is thre robux hacks### kjkytnfkyjglkbjttjlj

**Comment by cucumber25** [comment]
#40

**Comment by cucumber25** [comment]
> youtube.com

**Comment by cucumber25** [comment]
kl mb,tegfmb ,m.m gbml, jtmrmnk l;mt yhgkb jl; kmrtkj lf;gvm ;kjtyopdjfs dnyhcbopihe;l5j4wnr yfhb icop dl;ev.t5j4rnw sfxcbiop;lte jrn sdgoixbp;li'r kem54lrjksdgvlj mtemr,sdzxtf vjrk,mtndjfxkcgmh uibjkley5tirkmd gjhnvbkvj34whu5jrskmgdjvm jhtr,md,.gmj bdf

**Comment by cucumber25** [comment]
mung arew e friends

**Comment by cucumber25** [comment]
it's time to play football world cup world cup world cup world cup

**Comment by rxzyx** [comment]
Troll

**Comment by mungK11** [comment]
waht
