### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by Blooper-glooper** [rxzyx/Blooket-Hacks#273]
Rzx will we eventually get a new discord server?

**Comment by Angelio-Mustachio-Coder** [comment]
False issue.

**Comment by Blooper-glooper** [comment]
> False issue.

And?

**Comment by VillainsRule4000** [comment]
> False issue.

we're literally allowed to ask questions here now. shut your goofy ass up and get out. you claim to be a coder yet your only repository is literally an old copy of rzx's code. istg, retards on blooket...

**Comment by Wilke000** [comment]
Lol they don’t do they 😆

**Comment by rxzyx** [comment]
I got banned from discord xd, if I open another one I will get banned again. Do y'all want a guilded server?

**Comment by VillainsRule4000** [comment]
> I got banned from discord xd, if I open another one I will get banned again. Do y'all want a guilded server?

why banned?

**Comment by Blooper-glooper** [comment]
> I got banned from discord xd, if I open another one I will get banned again. Do y'all want a guilded server?

@rxzyx 𝕾𝖍𝖔𝖟𝖎𝖐𝖆𝖓 wants to give you one of his discord alts so you can have a discord account lmao, maybe we should make that guilded server.

**Comment by ZackiBoiz** [comment]
> I got banned from discord xd, if I open another one I will get banned again. Do y'all want a guilded server?

oh dang
