### ISSUE TITLE
[REQUEST]can you make a hack for crypto hack that lets you take any amount of crypto from another player

### ISSUE THREAD

**Issue by Esb678** [rxzyx/Blooket-Hacks#274]
You can take crypto from people

**Comment by Angelio-Mustachio-Coder** [comment]
Not sure this is possible. False issue.

**Comment by VillainsRule4000** [comment]
> Not sure this is possible. False issue.

it is, so shut your non-coding mouth.

**Comment by rxzyx** [comment]
It is possible. I'll consider.
