### ISSUE TITLE
Bug: Tower defense op tower not working

### ISSUE THREAD

**Issue by hacking-blooket-is-fun** [rxzyx/Blooket-Hacks#275]
**Describe the bug:**
I was showing my friend the hacks and I tried to use the op tower but the only thing my dragon did was spit out fire and didn't pop any balloons

**Screen recording:**
[Screen recording 2022-12-13 1.48.47 PM.webm](https://user-images.githubusercontent.com/120508434/207419656-03a5fba4-20c5-40a9-848a-0fa38b4970b2.webm)

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by rxzyx** [comment]
You use it after you place, I will nevertheless check this later.

**Comment by hacking-blooket-is-fun** [comment]
> You use it after you place, I will nevertheless check this later.

oooohhh thanks!
