### ISSUE TITLE
Someone stole your code and didn't give credit.

### ISSUE THREAD

**Issue by Consolehecker** [rxzyx/Blooket-Hacks#277]
https://github.com/codemaster123puppy/Blooket-Hacks-Working-Season-4- has stolen your add tokens and xp code.
Not really a bug

They probably stole other code too.

Wait how to i not mark it as bug

**Comment by rxzyx** [comment]
Ok thanks. But github won't do anything, I spent like 30m picking each stolen file for another person and they [GitHub support] never responded.

**Comment by Consolehecker** [comment]
Oh dang.

**Comment by Consolehecker** [comment]
> Ok thanks. But github won't do anything, I spent like 30m picking each stolen file for another person and they [GitHub support] never responded.

He just gave credit this morning
