### ISSUE TITLE
Bug: sosent work

### ISSUE THREAD

**Issue by 123Brk** [rxzyx/Blooket-Hacks#279]
**Describe the bug:**

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by Angelio-Mustachio-Coder** [comment]
False issue

**Comment by ZackiBoiz** [comment]
What doesn't work?

**Comment by A1gor1thm** [comment]
Sosent work guys :(
