### ISSUE TITLE
Bug: All Answers Correct

### ISSUE THREAD

**Issue by Ijustneedanaccountplease** [rxzyx/Blooket-Hacks#283]
**Describe the bug:**
When clicking on it, It doesn't do anything.

**Screen recording:**
https://drive.google.com/file/d/1xP66BL4puzy0Rjo3UYLOSPlp60cmshr0/view

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by codemaster123puppy** [comment]
Put it in Console in inspect element I don't think you can make all blooks a bookmark.

**Comment by ZackiBoiz** [comment]
If you need to make a hack usable as a bookmarklet (They should already be), use [this](https://caiorss.github.io/bookmarklet-maker/).
