### ISSUE TITLE
end game Bug: not working

### ISSUE THREAD

**Issue by Bugattiboi1000** [rxzyx/Blooket-Hacks#287]
**Describe the bug:**
says error when used

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by Angelio-Mustachio-Coder** [comment]
If you arent the host it doesnt work

**Comment by rxzyx** [comment]
^
