### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by RufusAL** [rxzyx/Blooket-Hacks#289]
**Describe the bug:**
its not a bug but i was just a bit confused about putting the hacks in the game if anyone could help me with that.

**Screen recording:**

*MAKE SURE THIS ISSUE IS CORRECT ACCORDING TO [THE RULES](https://github.com/rxzyx/Blooket-Hacks/issues/156)*

**Comment by ZackiBoiz** [comment]
Read the `README.md`
