### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by Unsspeakable** [rxzyx/Blooket-Hacks#294]
make a hack you can use for not getting kicked out of the game for hacking

**Comment by VillainsRule4000** [comment]
LMAO how does this make sense

**Comment by SillyBillylol10** [comment]
you mean anti ban they have that

**Comment by ZackiBoiz** [comment]
> make a hack you can use for not getting kicked out of the game for hacking

??? What?

Use the Anti-Ban hack

**Comment by Unsspeakable** [comment]
sorry
i thought that was for not getting ban from blooket not getting kicked out of the game
again sorry

**Comment by rxzyx** [comment]
^
