### ISSUE TITLE
Rxzyx Inactivity

### ISSUE THREAD

**Issue by ZackiBoiz** [rxzyx/Blooket-Hacks#296]
What's been going on lately? I'm really confused...

**Comment by Angelio-Mustachio-Coder** [comment]
Dead Repo?

**Comment by JaydenTD500** [comment]
could be

**Comment by Esb678** [comment]
Bruh

**Comment by uhhhhhhhhhhhhhh1** [comment]
Rxzyx is in russia so the war could be why

**Comment by rxzyx** [comment]
Hey - I'm fine! Just decided to focus on other things rather than my Github.

**Comment by Blooper-glooper** [comment]
> Hey - I'm fine! Just decided to focus on other things rather than my Github.

That's nice to hear
