### ISSUE TITLE
I want to suggest you add a feature where you can choose whatever pack you want, and you can choose what blook you get.[REQUEST]

### ISSUE THREAD

**Issue by TheOGLSS** [rxzyx/Blooket-Hacks#299]
**Describe the feature you want:**
 I want a feature where you can choose whatever blook you want to get from whetever pack you want so you dont have to only do it ingame

e.g. (open blooket market and paste hack) What pack do you want? (choose pack) What Blook? (choose blook) (and then it brings you to the pack opening screen ang gives you the blook)

**Comment by VillainsRule4000** [comment]
this isn't possible, idiot

**Comment by rxzyx** [comment]
Impossible.
