### ISSUE TITLE
'select any blook'

### ISSUE THREAD

**Issue by Saber-Tooth-Tiger** [rxzyx/Blooket-Hacks#3]
I know I am abit annyoing, but sorry, so the select any blook still doesn't work in the my blooks section in blook, nothing happened when I click the locked blooks :(

**Comment by rxzyx** [comment]
You clicked a blook that you have? You have to paste it before the host starts the game.

**Comment by Saber-Tooth-Tiger** [comment]
what do u mean?>

**Comment by Saber-Tooth-Tiger** [comment]
should I save the code in console or in the bookmarkelt

**Comment by Saber-Tooth-Tiger** [comment]
The end game only ends the game for me not the host

**Comment by rxzyx** [comment]
Select a blook that you have and then it will unlock it all.

**Comment by rxzyx** [comment]
Nope. I tried. It kicks EVERYONE out. It won’t say “Game Ended” though, but it does end the game.

**Comment by Saber-Tooth-Tiger** [comment]
Ok, thanks. yeah sorry, nvm, it works sorry for taking ur time! New to this!

**Comment by rxzyx** [comment]
Glad your problem was solved.
