### ISSUE TITLE
SCRIPT NOT WORKING FOR MONSTER BRAWL

### ISSUE THREAD

**Issue by NoDripGmoney** [rxzyx/Blooket-Hacks#40]
the all anwsers correct script doesnt work for monster brawl please fix the if you can!

**Comment by MrNoobb** [comment]
the god mode script works

**Comment by TheHelperMan** [comment]
Yeah, I'd say all work. Depends which exact one.

**Comment by NoDripGmoney** [comment]
all anwsers correct script

**Comment by rxzyx** [comment]
I’ll check the issue in a bit.
