### ISSUE TITLE
Anti-ban

### ISSUE THREAD

**Issue by Wilke000** [rxzyx/Blooket-Hacks#47]
Is there a way to unban yourself?

**Comment by VillainsRule4000** [comment]
No, anti-ban stops ban from happening in the first place. It doesn't unban.

**Comment by Wilke000** [comment]
or is it impossible

**Comment by rxzyx** [comment]
You can’t unban, the hack is for stopping a ban. Unfortunately you can’t really do anything to unban yourself.
