### ISSUE TITLE
how do you use plus

### ISSUE THREAD

**Issue by johnxinalikestoes** [rxzyx/Blooket-Hacks#53]

**Comment by johnxinalikestoes** [comment]
and plus dont work :(

**Comment by ZackiBoiz** [comment]
Copy the raw code in the file
Go to the live gamemode selection page
Run it in the console (Ctrl+Shift+J)
Choose a gamemode

**Comment by ZackiBoiz** [comment]
It should work

**Comment by johnxinalikestoes** [comment]
it dont work bc the live servers are down :(

**Comment by rxzyx** [comment]
Just because live servers are down doesn't mean it's my fault...

**Comment by rxzyx** [comment]
Reason for close: False Issue and Failure to understand purpose of hacks

**Comment by rxzyx** [comment]
It works. Tested.

**Comment by johnxinalikestoes** [comment]
ok i'll use when the servers are back up lol

**Comment by rxzyx** [comment]
You don't need to. It's plus hack, you are doing something wrong.

**Comment by johnxinalikestoes** [comment]
what am i doing wrong, and how do i do it?

**Comment by johnxinalikestoes** [comment]
nvm i just did it lol
