### ISSUE TITLE
Add Tokens Does Not Seem To Work.

### ISSUE THREAD

**Issue by TheHelperMan** [rxzyx/Blooket-Hacks#59]
The title says it all. I understand that it may not be possible to update it, as it interacts with the api, which seems to refuse doing so.

**Comment by Glixxzzy** [comment]
It's not working because you have to wait untill the timer on your stats page resets, Then It will work.
![Screenshot 2022-10-09 5 07 19 PM](https://user-images.githubusercontent.com/108609138/194779545-bc6a4318-2735-477a-968b-9848f4f8413b.png)

**Comment by Glixxzzy** [comment]
It works for me

**Comment by Glixxzzy** [comment]
![Screenshot 2022-10-09 5 13 54 PM](https://user-images.githubusercontent.com/108609138/194779799-77aed507-40e0-4131-b93a-461d7ffeda51.png)
When the daily tokens available says 500, then it will work.

**Comment by MoonMaster78** [comment]
It is not working even when I have 428 coins available.

**Comment by rxzyx** [comment]
Will be fixed soon

**Comment by VillainsRule4000** [comment]
Change the API call from api.blooket to dashboard.blooket...

**Comment by rxzyx** [comment]
Fixed. Uploading now.

**Comment by Tsmbah1** [comment]
Thank You it worked
