### ISSUE TITLE
Bot Flood

### ISSUE THREAD

**Issue by ZackiBoiz** [rxzyx/Blooket-Hacks#61]
The script doesn't flood the game.

**Comment by addasdasdasdasdasd** [comment]
the owner said that this will be looked into

**Comment by rxzyx** [comment]
I tried fixing it but couldn’t, but almost did! I’ll contact you when I’ve done it.

**Comment by VillainsRule4000** [comment]
Maybe change any API endpoints...

**Comment by rxzyx** [comment]
> Maybe change any API endpoints...

No. Endpoint for flood hasn't changed.

**Comment by rxzyx** [comment]
Oh btw, fixed.

**Comment by addasdasdasdasdasd** [comment]
it still does not work, it only puts in one bot.
