### ISSUE TITLE
Blooklet AutoBuy Blooks

### ISSUE THREAD

**Issue by GITHUBTRASHACCOUNT** [rxzyx/Blooket-Hacks#65]
ADD FEATURE

**Comment by Glixxzzy** [comment]
No they should add a feature where you can choose any blook you want on your avatar that would be cool

**Comment by VillainsRule4000** [comment]
@Glixxzzy that's not possible

**Comment by VillainsRule4000** [comment]
Also autobuy is named "Spam Open Boxes"

**Comment by rxzyx** [comment]
Already there
