### ISSUE TITLE
Bookmarklet

### ISSUE THREAD

**Issue by Instinct-YT** [rxzyx/Blooket-Hacks#7]
can you make it so it works for bookmarklet? my school blocked inspect.

**Comment by Angelio-Mustachio-Coder** [comment]
You just put it in the tab and it works
like put it in the website address, press enter and works'

**Comment by Instinct-YT** [comment]
> You just put it in the tab and it works like put it in the website address, press enter and works'

when I do that it google searches it.

**Comment by rxzyx** [comment]
javascript:ScriptCode

**Comment by rxzyx** [comment]
Then you are clearly in the wrong here.

**Comment by rxzyx** [comment]
Ctrl + shift + j or Cmd + option + J and paste the code in.

**Comment by rxzyx** [comment]
You have to be I Blooket to use the Blooket hacks.

**Comment by Instinct-YT** [comment]
> > > Then you are clearly in the wrong here.
> > 
> > 
> > how? i did exactly what you said.
> 
> Because Thousands of other people were able to use it successfully.

my school blocked inspect

**Comment by Instinct-YT** [comment]
yea if i right click it wont let me click inspect

**Comment by rxzyx** [comment]
> Ctrl + shift + j or Cmd + option + J and paste the code in.

I never said to right click.

**Comment by rxzyx** [comment]
Use the shortcut.

**Comment by Instinct-YT** [comment]
i did ctrl shift j it did not work

**Comment by rxzyx** [comment]
Inside chrome? Do you have mac or windows?

**Comment by rxzyx** [comment]
If that doesn’t work then you can’t fix it because it’s blocked.

**Comment by Instinct-YT** [comment]
yea it does not. is there any way you could make it so it works with bookmarks?

**Comment by rxzyx** [comment]
I might add bookmarklet support later but I’m busy rn.

**Comment by Instinct-YT** [comment]
ok. sorry that im being annoying.

**Comment by Instinct-YT** [comment]
and your wordle hacks are AMAZING

**Comment by rxzyx** [comment]
Thank you and it’s fine.

**Comment by Instinct-YT** [comment]
> Thank you and it’s fine.

hi just wanted to say can you email me when you have bookmark support? my email is shadowgalaxy061@gmail.com

**Comment by yedonbro** [comment]
> > Thank you and it’s fine.
> 
> hi just wanted to say can you email me when you have bookmark support? my email is [shadowgalaxy061@gmail.com](mailto:shadowgalaxy061@gmail.com)

https://caiorss.github.io/bookmarklet-maker/
type in the code and then drag the bookmarklet into your bookmarks bar
