### ISSUE TITLE
Token Hack

### ISSUE THREAD

**Issue by Wilke000** [rxzyx/Blooket-Hacks#70]
Token hack is broken... again

It shows that my daily tokens are 0 but no tokens were added when i entered the code

**Comment by rxzyx** [comment]
False issue. Tested yesterday.

**Comment by Tsmbah1** [comment]
It works it still works today in school I tried it and it worked

**Comment by Wilke000** [comment]
Oh well it doesn’t work for me

**Comment by Tsmbah1** [comment]
Well did you use it today?

**Comment by Wilke000** [comment]
Yes in the morning and yesterday

**Comment by Tsmbah1** [comment]
Then it wont work u can use it for only 1 day
