### ISSUE TITLE
Sell Dupes

### ISSUE THREAD

**Issue by Wilke000** [rxzyx/Blooket-Hacks#71]
Sell dupes shows this error when I run it, doesn't sell anything

<img width="617" alt="Screen Shot 2022-10-12 at 12 56 46 PM" src="https://user-images.githubusercontent.com/85253703/195403350-f0e2904c-b021-4e04-afab-cada150f270a.png">

**Comment by rxzyx** [comment]
False issue. Not made by me + use it in your blooks area, not anywhere else.

**Comment by rxzyx** [comment]
404 means not found, contact the contributor.

**Comment by Wilke000** [comment]
@VillainsRule4000?

**Comment by VillainsRule4000** [comment]
No, please don't @ me for no reason.

**Comment by Wilke000** [comment]
it wasn't for no reason why is there an error and can u fix it pls?

**Comment by VillainsRule4000** [comment]
It was, since I'm not wasting time fixing it. Contact the script creator.

**Comment by VillainsRule4000** [comment]
I have a life.

**Comment by Wilke000** [comment]
i thought u were the script creator

**Comment by Wilke000** [comment]
> I have a life.

i thought ur life was "mid"

**Comment by VillainsRule4000** [comment]
Look in the commit history. No clue what you mean about my life being "mid".

**Comment by Wilke000** [comment]
https://user-images.githubusercontent.com/85253703/195439325-f2db1f21-b36e-40dd-a995-1a17759e3e5a.mov

And ok i will

**Comment by Wilke000** [comment]
@ZackiBoiz can u fix this?

**Comment by VillainsRule4000** [comment]
> Screen.Recording.2022-10-12.at.4.16.05.PM.mov 
> And ok i will

My description has been "Why are you here?" for about a month now. Inspecting is cringe.

**Comment by Wilke000** [comment]
What? I didn't i swear it says "life is mid"

**Comment by Wilke000** [comment]
oh wait it just updated i swear I didn't inspect btw

**Comment by VillainsRule4000** [comment]
Why bother lying :skull:
Anyway, you're wasting my time.
![image](https://user-images.githubusercontent.com/101288516/195440750-a9208c41-0bc3-4c68-98ca-8541f98921ef.png)

**Comment by Wilke000** [comment]
. ok and btw: i didn't lie and I'm sticking to it! I AM AN HONEST MAN
