### ISSUE TITLE
Add max tokens 

### ISSUE THREAD

**Issue by gaelzayas** [rxzyx/Blooket-Hacks#77]
The script "add max tokens isn't working." It says it added the tokens yet doesn't do anything.
![blooket](https://user-images.githubusercontent.com/115113728/195634012-5acaaf26-0584-4d23-9a3a-d09ba64f2307.png)

**Comment by rxzyx** [comment]
Will be looked into. But note per 24 hrs

**Comment by rxzyx** [comment]
Fixed!
