### ISSUE TITLE
[BUG]Add token is broken

### ISSUE THREAD

**Issue by Jesse01px2029** [rxzyx/Blooket-Hacks#81]
**Describe the bug**

**To Reproduce**
Run the code, if there is an error, provide a screenshot or copy the error. However, if there is no error but it doesn't work then show the url on where it was made and how you ran the code.

**Comment by godlygamer123** [comment]
please fix add tokens does not work because the daily coins are not  reseting how do you fix dat

**Comment by godlygamer123** [comment]
need tokens quick

**Comment by Jesse01px2029** [comment]
I'm not the maker I'm just some like you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rxzyx** [comment]
I know.

**Comment by rxzyx** [comment]
Fixed!

**Comment by godlygamer123** [comment]
thanks very much
________________________________
