### ISSUE TITLE
[BUG] Add Tokens not working

### ISSUE THREAD

**Issue by vas12o3** [rxzyx/Blooket-Hacks#82]
**Describe the bug**

**To Reproduce**
Run the code, if there is an error, provide a screenshot or copy the error. However, if there is no error but it doesn't work then show the url on where it was made and how you ran the code.

**Comment by godlygamer123** [comment]
it is working but the tokens are not reseting

**Comment by godlygamer123** [comment]
which means it does not work

**Comment by rxzyx** [comment]
I know.

**Comment by rxzyx** [comment]
Fixed!
