### ISSUE TITLE
Max coins doesn't work [BUG]

### ISSUE THREAD

**Issue by aknadvabnjk** [rxzyx/Blooket-Hacks#83]
**Describe the bug**

**To Reproduce**
Run the code, if there is an error, provide a screenshot or copy the error. However, if there is no error but it doesn't work then show the url on where it was made and how you ran the code.

**Comment by Wilke000** [comment]
He is fixing it rn (maybe)

**Comment by Wilke000** [comment]
He knows

**Comment by rxzyx** [comment]
> He knows
> […](#)

Yes.

**Comment by rxzyx** [comment]
Fixed!
