### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Angelio-Mustachio-Coder** [rxzyx/Blooket-Hacks#85]
**Describe the bug**

**To Reproduce**
Run the code, if there is an error, provide a screenshot or copy the error. However, if there is no error but it doesn't work then show the url on where it was made and how you ran the code.
![image](https://user-images.githubusercontent.com/106037601/195903662-dab56c79-c512-418c-afeb-4e786d0af98f.png)
max tokens don't work

**Comment by rxzyx** [comment]
I know. I had like 200000 errors on this. Please stop.

**Comment by rxzyx** [comment]
Fixed!
