### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Hingchingchong** [rxzyx/Blooket-Hacks#87]
**Describe the bug**
i entered in the code and it said i was on the wrong page and so i clicked to go there and so i typed it in again and it still showed an error 
**To Reproduce**
Run the code, if there is an error, provide a screenshot or copy the error. However, if there is no error but it doesn't work then show the url on where it was made and how you ran the code.
![Screenshot 2022-10-14 222741](https://user-images.githubusercontent.com/115853659/195965038-f65a72dd-f64c-4ead-bbe1-2f98e3cb7a21.png)
![Screenshot 2022-10-14 223110](https://user-images.githubusercontent.com/115853659/195965043-77755a1c-9d24-4282-a108-574caf1b4059.png)

**Comment by Glixxzzy** [comment]
it works for me

**Comment by Hingchingchong** [comment]
i just tryed again and this time once it brings me to the join game page and i enter in the code it shows its added and then when i go back it doesnt show

**Comment by vantr-o** [comment]
> i just tryed again and this time once it brings me to the join game page and i enter in the code it shows its added and then when i go back it doesnt show

if its the get blooks thing thats only in game, what hack are you getting an error on?

**Comment by Hingchingchong** [comment]
> 

on the add tokens hack

**Comment by vantr-o** [comment]
works for me, my hacks work for me, youre just doing something wrong.

**Comment by rxzyx** [comment]
False issue. Code has to be run at play.boooket.com
