### ISSUE TITLE
GLIXXZY

### ISSUE THREAD

**Issue by Angelio-Mustachio-Coder** [rxzyx/Blooket-Hacks#9]
Hey Rx, Glixxzy is acting like he owns this app again, can we stop him by trying a takedown? others have had problems, but he is stealing your code,  And I have a suspicion that he has stolen them from you and called them his own and uploaded them to schoolcheats. You ARE the original creator and I won't stand for plagarism.

**Comment by rxzyx** [comment]
Yes I’m working on a DMCA Takedown goday.

**Comment by Angelio-Mustachio-Coder** [comment]
As a extra precaution, you should contact schoolcheats and inform them of this, and have them take the hacks down.

**Comment by rxzyx** [comment]
Yes but that’s not the real gliz. It’s lol-jude.

**Comment by glixxzzy** [comment]
You know, I have a story. I had LOL run my hacks until I knew it was safe, I almost got sued by the CEO of Blooket so I had someone run my hacks until it was safe to return, when he got into trouble being called a faker I came back.

**Comment by glixxzzy** [comment]
And the pictures you showed me were fake screenshots as of me checking!
