### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bannedagian** [rxzyx/Blooket-Hacks#92]
I was banned from blooket agian, I was just wondering if you could help lots of people out by making a hack to get us unbanned. also your add tokens hack didnt work and got me bannned

**Comment by rxzyx** [comment]
Unban hack is not possible. Plus failure to use ban prevention (Anti-Ban) hack. Read the main file (README.MD), I am not responsible with your usage of actions with the cheats.

**Comment by rxzyx** [comment]
Tokens was also tested, works fine.
