### ISSUE TITLE
Request, not a bug.

### ISSUE THREAD

**Issue by Angelio-Mustachio-Coder** [rxzyx/Blooket-Hacks#94]
Is there any way to create a script for the "battle royale" mode? or is it not workable?

**Comment by rxzyx** [comment]
Not an issue.

**Comment by rxzyx** [comment]
Not possible.

**Comment by myf20130** [comment]
> Not possible.

How is it not possible?

**Comment by VillainsRule4000** [comment]
@myf20130 Blooket has limits. This is part of the reason why you can't just get infinite tokens with hacks.
