### ISSUE TITLE
Candy Quest ESP [BUG]

### ISSUE THREAD

**Issue by ZackiBoiz** [rxzyx/Blooket-Hacks#99]
**Describe the bug**
The Candy Quest ESP (In the Gold Quest folder) doesn't show the values that are hiding behind the pumpkins. VillainsRule4000 said that the Gold Quest hacks work for Candy Quest too. (Which is true, other than ESP.)

**To Reproduce**
Run Chest ESP on a Candy Quest game.

**Comment by wilburcoding** [comment]
I am also experiencing this issue

**Comment by rxzyx** [comment]
Really silly issue coming from a 'coder'. Do you not know what HTML elements are?

**Comment by ZackiBoiz** [comment]
alr fine ill make one

**Comment by VillainsRule4000** [comment]
Well, yes, I didn't think about ESP. It should work fine for fetching the React values, just make sure it edits the DOM elements properly.
